// Job positions and companies data
export interface JobPosition {
  id: string
  name: string
  companies: string[]
}

export const jobPositions: JobPosition[] = [
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Twitter',
      'LinkedIn',
      'GitHub',
      'Atlassian',
      'Salesforce',
      'Adobe',
      'Oracle',
      'IBM',
      'Intel',
      'NVIDIA',
      'AMD',
      'Tesla',
      'SpaceX',
      'Palantir',
      'Snowflake',
      'Databricks',
      'MongoDB',
      'Redis',
      'Elastic',
      'Docker',
      'Kubernetes',
    ],
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Slack',
      'Figma',
      'Notion',
      'Airtable',
      'Asana',
      'Monday.com',
      'Trello',
      'Jira',
      'Confluence',
      'Miro',
      'InVision',
      'Sketch',
      'Adobe XD',
      'Principle',
      'Framer',
      'Webflow',
      'Squarespace',
      'Wix',
      'Shopify',
      'Stripe',
      'PayPal',
    ],
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'LinkedIn',
      'Palantir',
      'Snowflake',
      'Databricks',
      'Tableau',
      'Power BI',
      'Looker',
      'Qlik',
      'SAS',
      'IBM Watson',
      'H2O.ai',
      'DataRobot',
      'Alteryx',
      'RapidMiner',
      'KNIME',
      'Apache Spark',
      'Hadoop',
      'Kafka',
      'Elasticsearch',
      'MongoDB',
      'Redis',
    ],
  },
  {
    id: 'designer',
    name: 'Designer',
    companies: [
      'Apple',
      'Google',
      'Microsoft',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Figma',
      'Adobe',
      'Sketch',
      'InVision',
      'Principle',
      'Framer',
      'Webflow',
      'Squarespace',
      'Wix',
      'Canva',
      'Behance',
      'Dribbble',
      'Pinterest',
      'Instagram',
      'TikTok',
      'YouTube',
      'Vimeo',
      'Twitch',
      'Snapchat',
      'Twitter',
      'LinkedIn',
      'Facebook',
    ],
  },
  {
    id: 'marketing-manager',
    name: 'Marketing Manager',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'HubSpot',
    ],
  },
  {
    id: 'sales-manager',
    name: 'Sales Manager',
    companies: [
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Salesforce',
      'HubSpot',
    ],
  },
  {
    id: 'hr-manager',
    name: 'HR Manager',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Workday',
    ],
  },
  {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    companies: [
      'Goldman Sachs',
      'JPMorgan',
      'Morgan Stanley',
      'BlackRock',
      'Vanguard',
      'Fidelity',
      'Charles Schwab',
      'Wells Fargo',
      'Bank of America',
      'Citigroup',
    ],
  },
  {
    id: 'consultant',
    name: 'Consultant',
    companies: [
      'McKinsey',
      'BCG',
      'Bain',
      'Deloitte',
      'PwC',
      'EY',
      'KPMG',
      'Accenture',
      'IBM',
      'Capgemini',
    ],
  },
  {
    id: 'teacher',
    name: 'Teacher',
    companies: [
      'Harvard University',
      'Stanford University',
      'MIT',
      'Yale University',
      'Princeton University',
      'Columbia University',
      'University of Chicago',
      'Caltech',
      'Johns Hopkins',
      'Northwestern University',
    ],
  },
  {
    id: 'doctor',
    name: 'Doctor',
    companies: [
      'Mayo Clinic',
      'Cleveland Clinic',
      'Johns Hopkins Hospital',
      'Massachusetts General Hospital',
      'UCLA Medical Center',
      'Mount Sinai Hospital',
      'Stanford Health Care',
      'NYU Langone',
      'Cedars-Sinai',
      'UCSF Medical Center',
    ],
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    companies: [
      'Latham & Watkins',
      'Kirkland & Ellis',
      'Skadden',
      'Cravath',
      'Sullivan & Cromwell',
      'Davis Polk',
      'Simpson Thacher',
      'Paul Weiss',
      'Ropes & Gray',
      'Weil Gotshal',
    ],
  },
  {
    id: 'nurse',
    name: 'Nurse',
    companies: [
      'Mayo Clinic',
      'Cleveland Clinic',
      'Johns Hopkins Hospital',
      'Massachusetts General Hospital',
      'UCLA Medical Center',
      'Mount Sinai Hospital',
      'Stanford Health Care',
      'NYU Langone',
      'Cedars-Sinai',
      'UCSF Medical Center',
    ],
  },
  {
    id: 'accountant',
    name: 'Accountant',
    companies: [
      'Deloitte',
      'PwC',
      'EY',
      'KPMG',
      'Grant Thornton',
      'BDO',
      'RSM',
      'Crowe',
      'Baker Tilly',
      'Moss Adams',
    ],
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    companies: [
      'Google',
      'Microsoft',
      'Apple',
      'Amazon',
      'Meta',
      'Netflix',
      'Uber',
      'Airbnb',
      'Spotify',
      'Slack',
    ],
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst',
    companies: [
      'McKinsey',
      'BCG',
      'Bain',
      'Deloitte',
      'PwC',
      'EY',
      'KPMG',
      'Accenture',
      'IBM',
      'Capgemini',
    ],
  },
  {
    id: 'operations-manager',
    name: 'Operations Manager',
    companies: [
      'Amazon',
      'Walmart',
      'Target',
      'Costco',
      'Home Depot',
      "Lowe's",
      'FedEx',
      'UPS',
      'DHL',
      'PepsiCo',
    ],
  },
  {
    id: 'customer-service',
    name: 'Customer Service',
    companies: [
      'Amazon',
      'Apple',
      'Microsoft',
      'Google',
      'Meta',
      'Netflix',
      'Spotify',
      'Uber',
      'Airbnb',
      'Slack',
    ],
  },
  {
    id: 'content-creator',
    name: 'Content Creator',
    companies: [
      'YouTube',
      'TikTok',
      'Instagram',
      'Twitter',
      'LinkedIn',
      'Facebook',
      'Snapchat',
      'Pinterest',
      'Twitch',
      'Vimeo',
    ],
  },
  {
    id: 'photographer',
    name: 'Photographer',
    companies: [
      'Getty Images',
      'Shutterstock',
      'Adobe',
      'Canon',
      'Nikon',
      'Sony',
      'Fujifilm',
      'Panasonic',
      'Olympus',
      'Leica',
    ],
  },
  {
    id: 'chef',
    name: 'Chef',
    companies: [
      "McDonald's",
      'KFC',
      'Subway',
      'Pizza Hut',
      "Domino's",
      'Starbucks',
      'Chipotle',
      'Panera Bread',
      'Olive Garden',
      'Red Lobster',
    ],
  },
  {
    id: 'mechanic',
    name: 'Mechanic',
    companies: [
      'Ford',
      'General Motors',
      'Toyota',
      'Honda',
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Volkswagen',
      'Nissan',
      'Hyundai',
    ],
  },
  {
    id: 'electrician',
    name: 'Electrician',
    companies: [
      'General Electric',
      'Siemens',
      'Schneider Electric',
      'ABB',
      'Eaton',
      'Honeywell',
      'Emerson',
      'Rockwell Automation',
      'Johnson Controls',
      'Legrand',
    ],
  },
  {
    id: 'plumber',
    name: 'Plumber',
    companies: [
      'Roto-Rooter',
      'Mr. Rooter',
      'Benjamin Franklin Plumbing',
      'Ace Plumbing',
      'ServiceTitan',
      'Ferguson',
      'Wolseley',
      'HD Supply',
      'Ferguson Enterprises',
      'Winsupply',
    ],
  },
  {
    id: 'architect',
    name: 'Architect',
    companies: [
      'Gensler',
      'AECOM',
      'HOK',
      'Perkins&Will',
      'Skidmore, Owings & Merrill',
      'Foster + Partners',
      'Zaha Hadid Architects',
      'BIG',
      'Snøhetta',
      'MAD Architects',
    ],
  },
  {
    id: 'engineer',
    name: 'Engineer',
    companies: [
      'Boeing',
      'Lockheed Martin',
      'General Electric',
      'Siemens',
      'Honeywell',
      'Emerson',
      'Schneider Electric',
      'ABB',
      'Eaton',
      'Rockwell Automation',
    ],
  },
]

export async function fetchJobPositions(): Promise<JobPosition[]> {
  await new Promise((resolve) => setTimeout(resolve, 300))
  return jobPositions
}

export async function fetchCompaniesForPosition(positionId: string): Promise<string[]> {
  await new Promise((resolve) => setTimeout(resolve, 200))

  const position = jobPositions.find((p) => p.id === positionId)
  return position ? position.companies : []
}
