import type { Topic, University } from './types'

export const universitiesData: University[] = [
  {
    name: 'Hamedan University of Technology',
  },
  {
    name: 'Hekmat Private University Qom province',
  },
  {
    name: 'Abadan University of Medical Sciences',
  },
  {
    name: 'Al-Mustafa International University',
  },
  {
    name: 'Alzahra University',
  },
  {
    name: 'Ahvaz Jundishapur University of Medical Sciences',
  },
  {
    name: 'Ayatollah Borujerdi University',
  },
  {
    name: 'Comprehensive University of Technology, Tehran',
  },
  {
    name: 'Damghan University, Damghan',
  },
  {
    name: 'Danesh Alborz University, Qazvin',
  },
  {
    name: 'Hatef Higher Education Institute, Zahedan',
  },
  {
    name: 'Lamei Gorgani Institute of Higher Education',
  },
  {
    name: 'Farabi Institute of Virtual Higher Education',
  },
  {
    name: 'Farhangian University',
  },
  {
    name: 'Fasa University',
  },
  {
    name: 'Fasa University of Medical Sciences, Fasa',
  },
  {
    name: 'Fatemiye University of Medical Sciences, Qom',
  },
  {
    name: 'Ferdowsi University of Mashhad, Mashhad',
  },
  {
    name: 'Mohajer Technical University of Isfahan, Isfahan',
  },
  {
    name: 'Garmsar University',
  },
  {
    name: 'Gilan University of Medical Sciences',
  },
  {
    name: 'Golestan University, Gorgan',
  },
  {
    name: 'Golpayegan University of Engineering, Golpayegan',
  },
  {
    name: 'Gonabad University of Medical Sciences, Gonabad',
  },
  {
    name: 'Tabari Institute of Higher Education',
  },
  {
    name: 'Gonbad Kavous University, Golestan',
  },
  {
    name: 'Gorgan University of Agricultural Sciences and Natural Resources, Gorgan',
  },
  {
    name: 'Gorgan University of Medical Sciences',
  },
  {
    name: 'Hadith Science College, Tehran',
  },
  {
    name: 'Ilam University, Ilam',
  },
  {
    name: 'Medical University of Ilam, Ilam',
  },
  {
    name: 'Information and Communication Technology Faculty, Tehran',
  },
  {
    name: 'Industrial Management Institute, main campus Tehran, central campus Isfahan',
  },
  {
    name: 'Institute for Advanced Studies in Basic Sciences (IASBS), Zanjan',
  },
  {
    name: 'Institute for Higher Education ACECR Khouzestan, Ahvaz',
  },
  {
    name: 'Institute for Studies in Theoretical Physics and Mathematics (IPM)',
  },
  {
    name: 'International Institute of Earthquake Engineering and Seismology',
  },
  {
    name: 'International University of Chabahar',
  },
  {
    name: 'International University of Iran, Washington D.C.',
  },
  {
    name: 'Iran Informatic Institute (U.A.S.T., Tehran)',
  },
  {
    name: 'Iran Polymer and Petrochemical Institute',
  },
  {
    name: 'Iran University of Medical Sciences',
  },
  {
    name: 'Iran University of Science and Technology (IUST)',
  },
  {
    name: 'University of Science and Culture',
  },
  {
    name: 'Iraniyan Internet University (Tehran)',
  },
  {
    name: 'Iranian Space Research Center',
  },
  {
    name: 'Isfahan University of Art, Isfahan',
  },
  {
    name: 'Isfahan University of Medical Sciences',
  },
  {
    name: 'Islamic Azad University, Abhar',
  },
  {
    name: 'Islamic Azad University, Ahar Branch',
  },
  {
    name: 'Islamic Azad University, Ahvaz Branch',
  },
  {
    name: 'Islamic Azad University, Aliabad Katul',
  },
  {
    name: 'Islamic Azad University, Bandar Abbas',
  },
  {
    name: 'Islamic Azad University, Bojnourd Branch',
  },
  {
    name: 'Islamic Azad University, Bonab',
  },
  {
    name: 'Islamic Azad University, Central Tehran Branch',
  },
  {
    name: 'Islamic Azad University, Dezful Branch',
  },
  {
    name: 'Islamic Azad University, Eghlid Branch',
  },
  {
    name: 'Islamic Azad University, Estahban Branch',
  },
  {
    name: 'Islamic Azad University, Falavarjan Branch',
  },
  {
    name: 'Islamic Azad University, Firuzabad Branch',
  },
  {
    name: 'Islamic Azad University, Gachsaran Branch',
  },
  {
    name: 'Islamic Azad University, Garmsar Branch',
  },
  {
    name: 'Islamic Azad University, Gonabad Branch',
  },
  {
    name: 'Islamic Azad University, Hamedan Branch',
  },
  {
    name: 'Islamic Azad University, Khomain Branch',
  },
  {
    name: 'Islamic Azad University, Khomeyni Shahr Branch',
  },
  {
    name: 'Islamic Azad University, Isfahan (Khorasgan) Branch',
  },
  {
    name: 'Islamic Azad University, Khoy Branch',
  },
  {
    name: 'Islamic Azad University, Larestan Branch',
  },
  {
    name: 'Islamic Azad University, Mahabad Branch',
  },
  {
    name: 'Islamic Azad University, Majlesi Branch',
  },
  {
    name: 'Islamic Azad University, Maku Branch',
  },
  {
    name: 'Islamic Azad University, Maragheh Branch',
  },
  {
    name: 'Islamic Azad University, Marvdasht Branch',
  },
  {
    name: 'Islamic Azad University, Maybod Branch',
  },
  {
    name: 'Islamic Azad University, Miyaneh Branch',
  },
  {
    name: 'Islamic Azad University, Naein Branch',
  },
  {
    name: 'Islamic Azad University, Nishabur Branch',
  },
  {
    name: 'Islamic Azad University, Noor Branch',
  },
  {
    name: 'Islamic Azad University, Masjed Soleyman Branch',
  },
  {
    name: 'Islamic Azad University, Najafabad Branch',
  },
  {
    name: 'Islamic Azad University, Neyriz Branch',
  },
  {
    name: 'Islamic Azad University, Shahinshahr Branch',
  },
  {
    name: 'Islamic Azad University, Parand Branch',
  },
  {
    name: 'Qazvin Islamic Azad University',
  },
  {
    name: 'Islamic Azad University, Shahr-e-Qods Branch',
  },
  {
    name: 'Islamic Azad University, Qom Branch',
  },
  {
    name: 'Islamic Azad University, Quchan Branch',
  },
  {
    name: 'Islamic Azad University, Region One',
  },
  {
    name: 'Islamic Azad University Roudehen Branch',
  },
  {
    name: 'Islamic Azad University, Sabzevar Branch',
  },
  {
    name: 'Islamic Azad University, Sanandaj Branch',
  },
  {
    name: 'Islamic Azad University, Sari Branch',
  },
  {
    name: 'Islamic Azad University, Saveh Branch',
  },
  {
    name: 'Islamic Azad University, Science and Research Branch, Tehran (Tehran)',
  },
  {
    name: 'Islamic Azad University, West Tehran Branch',
  },
  {
    name: 'Islamic Azad University, Sepidan Branch',
  },
  {
    name: 'Islamic Azad University, Shabestar Branch',
  },
  {
    name: 'Islamic Azad University, Shahrood Branch',
  },
  {
    name: 'Islamic Azad University, Shiraz Branch',
  },
  {
    name: 'Islamic Azad University, Shirvan Branch',
  },
  {
    name: 'Islamic Azad University, Shoushtar Branch',
  },
  {
    name: 'Islamic Azad University, Sirjan Branch',
  },
  {
    name: 'Islamic Azad University, Tabriz Branch',
  },
  {
    name: 'Islamic Azad University, Tafresh Branch',
  },
  {
    name: 'Islamic Azad University, Takistan Branch',
  },
  {
    name: 'Islamic Azad University, North Tehran Branch',
  },
  {
    name: 'Islamic Azad University, South Tehran Branch',
  },
  {
    name: 'Islamic Azad University, Urmia Branch',
  },
  {
    name: 'Islamic Azad University, Varamin Branch',
  },
  {
    name: 'Islamic Azad University, Yasuj Branch',
  },
  {
    name: 'Islamic Azad University, Zanjan Branch',
  },
  {
    name: 'Islamic Azad University, Zarand Branch',
  },
  {
    name: 'Jahad Daneshgahi Academic Institute of Ahvaz',
  },
  {
    name: 'Kashan University of Medical Sciences',
  },
  {
    name: 'Kerman Khaje-Nasir Higher Education Center (K.K.H.E.C.), Kerman',
  },
  {
    name: 'Kerman University of Medical Sciences',
  },
  {
    name: 'Kermanshah University of Medical Sciences',
  },
  {
    name: 'Khorasan Institute of Higher Education, Mashhad',
  },
  {
    name: 'Khorramshahr University of Nautical Sciences and Technologies, Khorramshahr',
  },
  {
    name: 'Kish University (Kish Higher Education Institute)',
  },
  {
    name: 'Kordestan University of Medical Sciences, Sanandaj',
  },
  {
    name: 'Kowsar Institute of Higher Education / Kowsar Ghazvin Non-Profit Institute of Higher Education, Ghazvin',
  },
  {
    name: 'Lorestan University, Khorramabad',
  },
  {
    name: 'Lorestan University of Medical Sciences, Khorramabad',
  },
  {
    name: 'Malek-Ashtar University of Technology',
  },
  {
    name: 'Mashhad University of Medical Sciences',
  },
  {
    name: 'Mazandaran University of Medical Sciences, Sari',
  },
  {
    name: 'Mazandaran University of Science and Technology',
  },
  {
    name: 'Medical University for the Islamic Republic of Iran Army, Tehran',
  },
  {
    name: 'Medical University of Ilam',
  },
  {
    name: 'Mohaghegh Ardabili University',
  },
  {
    name: 'Montazeri Technical College of Mashhad',
  },
  {
    name: 'NAJA University of Police, Tehran',
  },
  {
    name: 'Nooretouba Virtual University, Tehran',
  },
  {
    name: 'Payame Noor University, Shiraz',
  },
  {
    name: 'Payame Noor University, Tabriz[permanent dead link]',
  },
  {
    name: 'Payame Noor University, Tehran',
  },
  {
    name: 'Payame Noor University, Urmia',
  },
  {
    name: 'Persian Gulf University',
  },
  {
    name: 'Petroleum University of Technology',
  },
  {
    name: 'Power and Water University of Technology, Tehran',
  },
  {
    name: 'Qazvin University of Medical Sciences',
  },
  {
    name: 'Qeshm Institute of Higher Education',
  },
  {
    name: "Qom Boy's Technical College",
  },
  {
    name: 'Qom University of Medical Sciences, Qom',
  },
  {
    name: 'Rafsanjan University of Medical Sciences',
  },
  {
    name: 'Raja University, Qazvin[12]',
  },
  {
    name: 'Razi University',
  },
  {
    name: 'The Research Institute of Hawzeh va Daneshgah',
  },
  {
    name: 'Sabzevar School of Medical Sciences, Sabzevar',
  },
  {
    name: 'Sadjad Institute of Higher Education, Mashhad',
  },
  {
    name: 'Safir Danesh University of Ilam',
  },
  {
    name: 'Sarab University of Medical Sciences',
  },
  {
    name: 'Sari Agricultural Sciences and Natural Resources University',
  },
  {
    name: 'School of International Relations (SIR), Tehran',
  },
  {
    name: 'Semnan University',
  },
  {
    name: 'Semnan University of Medical Sciences, Semnan',
  },
  {
    name: 'Shahab Danesh University (دانشگاه شهاب دانش)',
  },
  {
    name: 'Shahed University, Tehran',
  },
  {
    name: 'Shahed University of Medical Sciences, Tehran',
  },
  {
    name: 'Shahid Bahonar University of Kerman',
  },
  {
    name: 'Shahid Beheshti Teacher Training College',
  },
  {
    name: 'Shahid Beheshti University, Tehran',
  },
  {
    name: 'Shahid Beheshti University of Medical Sciences',
  },
  {
    name: 'Shahid Chamran University North Branch of Dezful',
  },
  {
    name: 'Shahid Chamran University of Ahvaz',
  },
  {
    name: 'Shahid Rajaee Teacher Training University, Tehran[13]',
  },
  {
    name: 'Shahid Sadoughi University of Medical Sciences and Health Services',
  },
  {
    name: 'Shahid Sattari University of Aeronautical Engineering, Tehran',
  },
  {
    name: 'Shahrekord University',
  },
  {
    name: 'Shahrekord University of Medical Sciences',
  },
  {
    name: 'Shahrood University of Technology',
  },
  {
    name: 'Shahroud University of Medical Sciences',
  },
  {
    name: 'Shariaty Technical College, Tehran',
  },
  {
    name: 'Sharif University of Technology, International Campus – Kish',
  },
  {
    name: 'Sheikhbahaee institute of higher education, Isfahan',
  },
  {
    name: 'Shomal University',
  },
  {
    name: 'Soore University',
  },
  {
    name: 'Taali Institute of HigherEducation, Qom (مؤسسه آموزش عالی تعالی)',
  },
  {
    name: 'Tabarestan University (Tabarestan Higher Education Institution)',
  },
  {
    name: 'Tabriz Islamic Art University, Tabriz',
  },
  {
    name: 'Tabriz University of Medical Sciences',
  },
  {
    name: 'Tafresh University, Tafresh',
  },
  {
    name: 'Tarbiat Moallem University of Sabzevar, Sabzevar',
  },
  {
    name: 'Tarbiat Modares University (Professor Training University)',
  },
  {
    name: 'Tehran University of Medical Sciences',
  },
  {
    name: 'Technical and Vocational University',
  },
  {
    name: 'Tehran University of Medical Sciences – International Campus (TUMS-IC)',
  },
  {
    name: 'Torbat Heydarieh University of Medical Sciences',
  },
  {
    name: 'University College of Nabi Akram, Tabriz',
  },
  {
    name: 'University of Applied Science and Technology',
  },
  {
    name: 'University of Bonab',
  },
  {
    name: 'University of Defence Sciences and Technologies, Isfahan',
  },
  {
    name: 'University of Economic sciences, Tehran',
  },
  {
    name: 'University of Guilan',
  },
  {
    name: 'University of Isfahan',
  },
  {
    name: 'University of Kordestan',
  },
  {
    name: 'University of Mazandaran',
  },
  {
    name: 'University of Qom',
  },
  {
    name: 'University of Sistan and Baluchestan',
  },
  {
    name: 'University of Social Welfare and Rehabilitation Sciences, Tehran',
  },
  {
    name: 'University of Tabriz, Tabriz',
  },
  {
    name: 'University of Tehran, Tehran',
  },
  {
    name: 'University of Zabol, Zabol',
  },
  {
    name: 'University of Zanjan',
  },
  {
    name: 'Urmia University',
  },
  {
    name: 'Urmia University of Medical Sciences',
  },
  {
    name: 'Urmia University of Technology',
  },
  {
    name: 'ValiAsr University of Rafsanjan (Vali-E-Asr), Rafsanjan',
  },
  {
    name: 'Yasuj University, Yasuj',
  },
  {
    name: 'Yasuj University of Medical Sciences',
  },
  {
    name: 'Yazd Institute of Higher Education, ACECR',
  },
  {
    name: 'Zahedan University of Medical Sciences, Zahedan',
  },
  {
    name: 'Zanjan University of Medical Sciences, Zanjan',
  },
  {
    name: 'Kharazmi University, Karaj Campus',
  },
  {
    name: 'Tehran University of Art',
  },
  {
    name: 'Alborz University of Medical Sciences',
  },
  {
    name: 'Islamic Azad University, Karaj Branch',
  },
  {
    name: 'Islamic Azad University, Hashtgerd Branch',
  },
  {
    name: 'Payame Noor University of Karaj',
  },
  {
    name: 'Payame Noor University of Hashtgerd',
  },
  {
    name: 'Payame Noor University of Eshtehard',
  },
  {
    name: 'Payame Noor University of Nazarabad',
  },
  {
    name: 'Rasam Institute of Higher Education',
  },
  {
    name: 'Farabi Institute of Higher Education',
  },
  {
    name: 'Ardabil University of Medical Sciences',
  },
  {
    name: 'Islamic Azad University, Ardabil Branch',
  },
  {
    name: 'Islamic Azad University, Khalkhal Branch',
  },
  {
    name: 'Azarbaijan University of Tarbiat Moallem',
  },
  {
    name: 'Sahand University of Technology',
  },
  {
    name: 'Tabriz College of Technology',
  },
  {
    name: 'Tabriz Islamic Art University',
  },
  {
    name: 'University College of Mizan',
  },
  {
    name: 'University College of Nabi Akram',
  },
  {
    name: 'Sarab University of Medical Sciences [1]',
  },
  {
    name: 'Azarbaijan Shahid Madani University',
  },
  {
    name: 'University of Maragheh',
  },
  {
    name: 'Islamic Azad University, Ilkhchi Branch',
  },
  {
    name: 'Islamic Azad University, Marand Branch Branch',
  },
  {
    name: 'Islamic Azad University, Osku Branch',
  },
  {
    name: 'Islamic Azad University, Sofian Branch',
  },
  {
    name: 'Payam-e-Nour University of Tabriz',
  },
  {
    name: 'Tabriz Islamic Arts University',
  },
  {
    name: 'Islamic Azad University, Miandoab Branch',
  },
  {
    name: 'Islamic Azad University, Khoy Branch[permanent dead link]',
  },
  {
    name: 'Payame Noor University, Maku',
  },
  {
    name: 'Islamic Azad University, Salmas Branch',
  },
  {
    name: 'Bushehr University of Medical Sciences',
  },
  {
    name: 'Imam Khamenei Junior Technical College of Bushehr',
  },
  {
    name: 'Islamic Azad University, Bushehr Branch',
  },
  {
    name: 'Islamic Azad University, Khark Branch',
  },
  {
    name: 'Chahar Mahaal va Bakhtiari',
  },
  {
    name: 'Islamic Azad University, Borujen Branch',
  },
  {
    name: 'Islamic Azad Un  iversity, Farsan Branch',
  },
  {
    name: 'Islamic Azad University, Shahrekord Branch',
  },
  {
    name: 'Shiraz University',
  },
  {
    name: 'Shiraz University of Medical Sciences',
  },
  {
    name: 'Shiraz University of Technology',
  },
  {
    name: 'Salman Farsi University of Kazerun',
  },
  {
    name: 'Islamic Azad University, Jahrom Branch',
  },
  {
    name: 'Fasa University of Medical Sciences',
  },
  {
    name: 'Bahonar College of Technology and Engineering of Shiraz',
  },
  {
    name: 'Islamic Azad University, Science and Research Branch, Fars',
  },
  {
    name: 'Islamic Azad University, Abadeh Branch',
  },
  {
    name: 'Islamic Azad University, Arsanjan Branch',
  },
  {
    name: 'Islamic Azad University, Fasa Branch',
  },
  {
    name: 'Islamic Azad University, Firouzabad Branch',
  },
  {
    name: 'Islamic Azad University, Kazerun Branch',
  },
  {
    name: 'Pasargad Institute of Higher Education',
  },
  {
    name: 'Zand Institute of Higher Education',
  },
  {
    name: 'Deylaman Institute of Higher Education',
  },
  {
    name: 'Ghadr Institute of Higher Education',
  },
  {
    name: 'Institute of Higher Education for Academic Jihad of Rasht',
  },
  {
    name: 'Kadous Institute of Higher Education',
  },
  {
    name: 'Islamic Azad University, Astara Branch',
  },
  {
    name: 'Islamic Azad University, Bandar Anzali Branch',
  },
  {
    name: 'Islamic Azad University, Rasht Branch',
  },
  {
    name: 'Jaber-Ebn-E-Hayyan',
  },
  {
    name: 'University of Gilan',
  },
  {
    name: 'Golestan University',
  },
  {
    name: 'Gonbad Kavous University',
  },
  {
    name: 'Gorgan University of Agricultural Sciences and Natural Resources',
  },
  {
    name: 'Golestan University of Medical Sciences, Gorgan',
  },
  {
    name: 'Islamic Azad University, Gorgan Branch',
  },
  {
    name: 'Bu-Ali Sina University',
  },
  {
    name: 'Electrical Engineering University',
  },
  {
    name: 'Islamic Azad University, Malayer Branch',
  },
  {
    name: 'Islamic Azad University, Tuyserkan Branch',
  },
  {
    name: 'University of Malayer',
  },
  {
    name: 'University of Medical Sciences of Hamedan',
  },
  {
    name: 'Hormozgan',
  },
  {
    name: 'Bandar Abbas University of Medical Sciences',
  },
  {
    name: 'Hormozgan University',
  },
  {
    name: 'Kish University',
  },
  {
    name: 'Ilam University',
  },
  {
    name: 'Islamic Azad University, Ilam Branch',
  },
  {
    name: 'Jihad Daneshgahi Institute of Higher Education (ACECR)',
  },
  {
    name: 'Allameh Feiz Kashani Institute of Higher Education',
  },
  {
    name: 'Shahid Ashrafi Isfahani Institute of Higher Education',
  },
  {
    name: 'Daneshpazhoohan Institute of Higher Education (مؤسسه آموزش عالی دانش‌پژوهان)',
  },
  {
    name: 'Golpayegan University of Engineering',
  },
  {
    name: 'Isfahan University of Art',
  },
  {
    name: 'Isfahan University of Social Welfare and Rehabilitation Sciences[permanent dead link]',
  },
  {
    name: 'Isfahan University of Technology (دانشگاه صنعتی اصفهان)',
  },
  {
    name: 'Mohajer Technical University of Isfahan (MTU) (دانشکده فنی مهاجر اصفهان)',
  },
  {
    name: 'Islamic Azad University, Felavarjan Branch',
  },
  {
    name: 'Islamic Azad University, Golpayegan Branch',
  },
  {
    name: 'Islamic Azad University, Kashan Branch (دانشگاه آزاد اسلامی واحد كاشان)',
  },
  {
    name: 'Islamic Azad University, Maymeh Branch',
  },
  {
    name: 'Islamic Azad University, Mobarakeh Branch',
  },
  {
    name: 'Islamic Azad University, Naeen Branch',
  },
  {
    name: 'Islamic Azad University, Shahreza Branch',
  },
  {
    name: 'Jami Institute of Technology',
  },
  {
    name: 'Kashan Shahid Rajaee Technical College of T.V.U',
  },
  {
    name: 'Shahreza Higher Education Center (مرکز آموزش عالی شهرضا)',
  },
  {
    name: 'Sheikhbahaee University (دانشگاه شیخ بهایی)',
  },
  {
    name: 'University of Defence Sciences and Technologies',
  },
  {
    name: 'Besat Institute of Higher Education of Kerman',
  },
  {
    name: 'Islamic Azad University, Anar Branch',
  },
  {
    name: 'Islamic Azad University, Baft Branch',
  },
  {
    name: 'Islamic Azad University, Bam Branch',
  },
  {
    name: 'Islamic Azad University, Bardsir Branch',
  },
  {
    name: 'Islamic Azad University, Jiroft Branch',
  },
  {
    name: 'Islamic Azad University, Kerman Branch',
  },
  {
    name: 'Islamic Azad University, Rafsanjan Branch',
  },
  {
    name: 'Islamic Azad University, Shahr Babak Branch',
  },
  {
    name: 'Jiroft University',
  },
  {
    name: 'Rafsanjan University of Vali Asr',
  },
  {
    name: 'Sirjan University of Technology',
  },
  {
    name: 'Islamic Azad University, Kermanshah Branch',
  },
  {
    name: 'Kermanshah University of Technology',
  },
  {
    name: 'Jahad Daneshgahi of Kermanshah',
  },
  {
    name: 'Khorasan, North',
  },
  {
    name: 'Hakiman Institute of Human Science',
  },
  {
    name: 'Esfarayen University of Technology',
  },
  {
    name: 'Islamic Azad University, Shiravan Branch',
  },
  {
    name: 'University of Bojnord',
  },
  {
    name: 'Eqbal Lahoori Institute of Higher Education',
  },
  {
    name: 'Ferdowsi University of Mashhad',
  },
  {
    name: 'Gonabad University of Medical Sciences',
  },
  {
    name: 'Imam Reza University',
  },
  {
    name: 'Iranian Academic Center for Education, Culture and Research, Mashhad Branch (Jahad Daneshgahi of Mashhad)',
  },
  {
    name: 'Islamic Azad University, Mashhad Branch',
  },
  {
    name: 'Islamic Azad University, Neishabur Branch',
  },
  {
    name: 'Islamic Azad University, Torbat e Jam',
  },
  {
    name: 'Islamic Azad University, Torbat Heidariyeh Branch',
  },
  {
    name: 'Quchan University of Advanced Technologies Engineering',
  },
  {
    name: 'Sabzevar Teacher Training University',
  },
  {
    name: 'Sabzevar University of Medical Sciences',
  },
  {
    name: 'Salman Institute of Higher Education',
  },
  {
    name: 'University of Torbat Heydarieh',
  },
  {
    name: 'University of Neyshabur[18]',
  },
  {
    name: 'Islamic Azad University, Birjand Branch',
  },
  {
    name: 'Islamic Azad University, Ferdows Branch',
  },
  {
    name: 'University of Birjand',
  },
  {
    name: 'Ahvaz Payam Noor University',
  },
  {
    name: 'Islamic Azad University, Abadan Branch',
  },
  {
    name: 'Islamic Azad University, Behbahan Branch',
  },
  {
    name: 'Islamic Azad University, Izeh Branch',
  },
  {
    name: 'Islamic Azad University, Omidieh Branch',
  },
  {
    name: 'Islamic Azad University – Science & Research Branch, Khuzestan',
  },
  {
    name: 'Institute for Higher Education ACECR Khouzestan',
  },
  {
    name: 'Jundishapor University of Dezful',
  },
  {
    name: 'Khorramshahr University of Natural Sciences and Technologies',
  },
  {
    name: 'Persian Gulf International Education Center',
  },
  {
    name: 'Rahnama Institute of Higher Education',
  },
  {
    name: 'Payame Noor University of Ahvaz',
  },
  {
    name: 'Amiralmoemenin University',
  },
  {
    name: 'University of Yasuj',
  },
  {
    name: 'Farhangian University of Sanandaj',
  },
  {
    name: 'Kurdistan University of Medical Sciences',
  },
  {
    name: 'Payam Noor University of Bijar Garrus',
  },
  {
    name: 'Grand Ayatollah Borujerdi University, University of Ayatollah ozma Boroujerdi',
  },
  {
    name: 'Islamic Azad University, Aligudarz Branch',
  },
  {
    name: 'Islamic Azad University, Borujerd Branch',
  },
  {
    name: 'Islamic Azad University, Khorramabad Branch',
  },
  {
    name: 'Lorestan University',
  },
  {
    name: 'Lorestan University of Medical Sciences',
  },
  {
    name: 'Shahid Madani Technical and Vocational College',
  },
  {
    name: 'AmirKabir University of Technical Works (Amouzesh Ali Fani)',
  },
  {
    name: 'Arak University',
  },
  {
    name: 'Arak University of Medical Sciences',
  },
  {
    name: 'Iran University of Science and Technology (Arak Campus)',
  },
  {
    name: 'Islamic Azad University, Arak Branch',
  },
  {
    name: 'Islamic Azad University, Ashtian Branch',
  },
  {
    name: 'Islamic Azad University, Farahan Branch',
  },
  {
    name: 'Islamic Azad University, Khomein Branch',
  },
  {
    name: 'Tarbiat Moallem University of Arak',
  },
  {
    name: 'Mazandaran Institute of Technology (مؤسسه اموزش عالی صنعتی مازندران)',
  },
  {
    name: 'farvardin institute of higher education (مؤسسه آموزش عالی فروردین قائمشهر)',
  },
  {
    name: 'Allame Mohaddes Noori University (دانشگاه علامه محدث نوری)',
  },
  {
    name: 'Babol Noshirvani University of Technology (دانشگاه صنعتی نوشیروانی بابل)',
  },
  {
    name: 'Babol University of Medical Sciences',
  },
  {
    name: 'Behshahr University of Science and Technology',
  },
  {
    name: 'Imam Khomeini University for Naval Sciences',
  },
  {
    name: 'Islamic Azad University, Nour Branch (دانشگاه آزاد اسلامي واحد نور)',
  },
  {
    name: 'Islamic Azad University, Tonekabon Branch',
  },
  {
    name: 'Khazar University (دانشگاه خزر)',
  },
  {
    name: 'Maziar University (دانشگاه مازیار – نور)',
  },
  {
    name: 'Alvand Payam Noor University[permanent dead link]',
  },
  {
    name: 'Kar higher education institute',
  },
  {
    name: 'Danesh Alborz University',
  },
  {
    name: 'Imam Khomeini International University',
  },
  {
    name: 'Islamic Azad University, Takestan Branch',
  },
  {
    name: 'Islamic Kar University',
  },
  {
    name: 'Raja University, Qazvin[19]',
  },
  {
    name: 'Shahid Babaee Technical Institute',
  },
  {
    name: 'Sohrevardi Institute of Higher Education (مؤسسه آموزش عالی سهروردی قزوین)',
  },
  {
    name: 'Hekmat Private University',
  },
  {
    name: 'Payame Noor University of Qom (Qom Payame Noor University',
  },
  {
    name: 'Computer Research Center of Islamic Sciences, Qom',
  },
  {
    name: 'Fatemieh University of Medical Sciences',
  },
  {
    name: 'Mofid University',
  },
  {
    name: 'Shahab Danesh Institute of higher education (مؤسسه آموزش عالی شهاب دانش)',
  },
  {
    name: 'University of Religions and Denominations',
  },
  {
    name: 'Qom University of Technology',
  },
  {
    name: 'Damghan University',
  },
  {
    name: 'Eyvanekey University',
  },
  {
    name: 'Islamic Azad University, Semnan Branch',
  },
  {
    name: 'Semnan University of Medical Sciences',
  },
  {
    name: 'Sistan And Baluchistan',
  },
  {
    name: 'Hatef Institute of Higher Education, Zahedan[21]',
  },
  {
    name: 'International University of Chabahar[22]',
  },
  {
    name: 'Zabol University of Medical Sciences (دانشگاه علوم پزشکی زابل)',
  },
  {
    name: 'Zahedan University of Medical Sciences',
  },
  {
    name: 'Velayat University',
  },
  {
    name: 'Enghelab-e Eslami Technical College',
  },
  {
    name: 'Abbaspour University of Technology',
  },
  {
    name: 'Alborz University of Information & Communication of Technology',
  },
  {
    name: 'Allameh Tabatabaii University',
  },
  {
    name: 'Amirkabir University of Technology (Tehran Polytechnic)',
  },
  {
    name: 'Art University of Tehran (Persian: دانشگاه هنر تهران)',
  },
  {
    name: 'Aviation Industry Training Center – AITC',
  },
  {
    name: 'Bagher Aloloum University',
  },
  {
    name: 'Baqiyatallah Medical Sciences University',
  },
  {
    name: 'Civil Aviation Technology College',
  },
  {
    name: 'Comprehensive University of Technology',
  },
  {
    name: 'Computer College of National Organization of Educational Testing',
  },
  {
    name: 'DPI College (ex IBM college)',
  },
  {
    name: 'Hadith College of Tehran',
  },
  {
    name: 'Higher Education Center for Cultural Heritage',
  },
  {
    name: 'Imam Ali University for Army Officers',
  },
  {
    name: 'Imam Hossein University',
  },
  {
    name: 'Imam Sadeq University (ISU)',
  },
  {
    name: 'International University of Iran',
  },
  {
    name: 'Iran Broadcasting University',
  },
  {
    name: 'Iran College of Tele-communications',
  },
  {
    name: 'Iran University Science and Culture University',
  },
  {
    name: 'Iran University of Science and Technology',
  },
  {
    name: 'Iranian Business School',
  },
  {
    name: 'Islamic Azad University, Damavand Branch',
  },
  {
    name: 'Islamic Azad University, Roodehen Branch',
  },
  {
    name: 'Islamic Azad University, Tehran Dental Branch',
  },
  {
    name: 'Islamic Azad University, East Tehran Branch',
  },
  {
    name: 'Islamic Azad University, Tehran Medical Branch',
  },
  {
    name: 'Islamic Azad University, Shahr-e-Rey Branch',
  },
  {
    name: 'Islamic Azad University Science and Research Branch',
  },
  {
    name: 'Jahad Daneshgahi University',
  },
  {
    name: 'Kharazmi University',
  },
  {
    name: 'K.N.Toosi University of Technology',
  },
  {
    name: 'Payame Noor University',
  },
  {
    name: 'Power and Water University of Technology',
  },
  {
    name: 'School of International Relations (SIR)',
  },
  {
    name: 'Shahed University',
  },
  {
    name: 'Shahid Beheshti University',
  },
  {
    name: 'Shahid Rajaee Teacher Training University',
  },
  {
    name: 'Shahid Sattari University of Aeronautical Engineering',
  },
  {
    name: 'Shahid Shamsipour Institute of Technology',
  },
  {
    name: 'Shariaty Technical College',
  },
  {
    name: 'Sharif University of Technology',
  },
  {
    name: 'Tehran College of Environment',
  },
  {
    name: 'Tehran University of Medical Sciences, International Campus',
  },
  {
    name: 'University of Economic Sciences',
  },
  {
    name: 'University of Emam Reza',
  },
  {
    name: 'University of Ershad Damavand',
  },
  {
    name: 'University of Islamic Sects',
  },
]
// Helper function to create slug-like ID from English title
function createTopicId(titleEn: string): string {
  return titleEn
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '') // Remove special characters except spaces and hyphens
    .replace(/\s+/g, '_') // Replace spaces with underscores
    .replace(/-/g, '_') // Replace hyphens with underscores
    .replace(/_+/g, '_') // Replace multiple underscores with single underscore
    .replace(/^_|_$/g, '') // Remove leading/trailing underscores
}

function createTopic(titleEn: string, universities: University[] = universitiesData): Topic {
  return {
    id: createTopicId(titleEn),
    name: titleEn,
    universities,
  }
}

const topicTitles = [
  'Accounting',
  'Accounting Technology/Technician and Bookkeeping',
  'Accounting and Business/Management',
  'Accounting and Computer Science',
  'Accounting and Finance',
  'Acoustics',
  'Acting',
  'Actuarial Science',
  'Actuary',
  'Acupuncture and Oriental Medicine',
  'Administration of Special Education',
  'Administrative Assistant and Secretarial Science',
  'Adult Development and Aging',
  'Adult Health Nurse/Nursing',
  'Adult Literacy Tutor/Instructor',
  'Adult and Continuing Education Administration',
  'Adult and Continuing Education and Teaching',
  'Adult education',
  'Advanced General Dentistry',
  'Advanced Legal Research/Studies',
  'Advertising',
  'Aerodynamics engineering',
  'Aeronautical and flight maintenance engineering',
  'Aeronautical/Aerospace Engineering Technology/Technician',
  'Aeronautics/Aviation/Aerospace Science and Technology',
  'Aerospace Ground Equipment Technology',
  'Aerospace Physiology and Medicine',
  'Aerospace engineering',
  'Aerospace, Aeronautical and Astronautical/Space Engineering',
  'Aesthetician/Esthetician and Skin Care Specialist',
  'African Languages, Literatures, and Linguistics',
  'African Studies',
  'African-American/Black Studies',
  'Agribusiness/Agricultural Business Operations',
  'Agricultural Animal Breeding',
  'Agricultural Business Technology',
  'Agricultural Business and Management',
  'Agricultural Communication/Journalism',
  'Agricultural Economics',
  'Agricultural Mechanics and Equipment/Machine Technology',
  'Agricultural Power Machinery Operation',
  'Agricultural Production Operations',
  'Agricultural Teacher Education',
  'Agricultural and Extension Education Services',
  'Agricultural and Food Products Processing',
  'Agricultural and Horticultural Plant Breeding',
  'Agricultural engineering',
  'Agricultural engineering - agricultural economics',
  'Agricultural engineering - agricultural education & extension',
  'Agricultural engineering - plant pathology',
  'Agricultural machineries',
  'Agricultural mechanization',
  'Agricultural mechanization engineering',
  'Agricultural/Farm Supplies Retailing and Wholesaling',
  'Agriculture engineering - agronomy',
  'Agriculture engineering - animal sciences',
  'Agriculture engineering - biotechnology',
  'Agriculture engineering - horticultural sciences',
  'Agroecology and Sustainable Agriculture',
  'Agronomy and Crop Science',
  'Air Traffic Controller',
  'Air and Space Operations Technology',
  'Aircraft Armament Systems Technology',
  'Aircraft Powerplant Technology/Technician',
  'Aircraft maintenance engineering',
  'Aircraft structural integrity program',
  'Airframe Mechanics and Aircraft Maintenance Technology/Technician',
  'Airline Flight Attendant',
  'Airline/Commercial/Professional Pilot and Flight Crew',
  'Albanian Language and Literature',
  'Algebra and Number Theory',
  'Algorithms and computation',
  'Alternative Fuel Vehicle Technology/Technician',
  'American  History (United States)',
  'American Government and Politics (United States)',
  'American Indian/Native American Languages, Literatures, and Linguistics',
  'American Indian/Native American Studies',
  'American Literature (Canadian)',
  'American Literature (United States)',
  'American Sign Language (ASL)',
  'American/US Law/Legal Studies/Jurisprudence',
  'American/United States Studies/Civilization',
  'Analysis and Functional Analysis',
  'Analytical chemistry',
  'Anatomy',
  'Ancient Near Eastern and Biblical Languages, Literatures, and Linguistics',
  'Ancient Studies/Civilization',
  'Ancient iranian languages',
  'Ancient/Classical Greek Language and Literature',
  'Anesthesiologist Assistant',
  'Anesthesiology',
  'Animal Behavior and Ethology',
  'Animal Genetics',
  'Animal Health',
  'Animal Nutrition',
  'Animal Physiology',
  'Animal Sciences',
  'Animal Training',
  'Animal-Assisted Therapy',
  'Animal/Livestock Husbandry and Production',
  'Animation',
  'Animation, Interactive Technology, Video Graphics and Special Effects',
  'Anthropology',
  'Apparel and Accessories Marketing Operations',
  'Apparel and Textile Manufacture',
  'Apparel and Textile Marketing Management',
  'Apparel and Textiles',
  'Apparel and textile design',
  'Appliance Installation and Repair Technology/Technician',
  'Applied Economics',
  'Applied Horticulture/Horticulture Operations',
  'Applied Linguistics',
  'Applied and Professional Ethics',
  'Applied chemistry',
  'Applied mathematics',
  'Appraisal',
  'Aquaculture',
  'Aquatic Biology/Limnology',
  'Arabic language and literature',
  'Arabic translation',
  'Archeology',
  'Architectural Drafting and Architectural CAD/CADD',
  'Architectural Engineering',
  'Architectural Engineering Technology/Technician',
  'Architectural History and Criticism',
  'Architectural Technology/Technician',
  'Architectural and Building Sciences/Technology',
  'Architecture',
  'Architecture technology',
  'Archives/Archival Administration',
  'Aromatherapy',
  'Art History, Criticism and Conservation',
  'Art Teacher Education',
  'Art Therapy/Therapist',
  'Art research',
  'Art/Art Studies',
  'Artifical intelligence and robotics engineering',
  'Artificial Intelligence',
  'Artificial intelligence and robotics',
  'Arts, Entertainment,and Media Management',
  'Asian Bodywork Therapy',
  'Asian History',
  'Asian Studies/Civilization',
  'Asian-American Studies',
  'Assistive/Augmentative Technology and Rehabilitation Engineering',
  'Astronomy',
  'Astrophysics',
  'Athletic Training/Trainer',
  'Atmospheric Chemistry and Climatology',
  'Atmospheric Physics and Dynamics',
  'Atmospheric Sciences and Meteorology',
  'Atmospheric sciences',
  'Atomic, molecular & optical physics',
  'Atomic/Molecular Physics',
  'Auctioneering',
  'Audiology',
  'Audiology/Audiologist',
  'Audiology/Audiologist and Speech-Language Pathology/Pathologist',
  'Auditing',
  'Australian/Oceanic/Pacific Languages, Literatures, and Linguistics',
  'Autobody/Collision and Repair Technology/Technician',
  'Automation Engineer Technology/Technician',
  'Automobile/Automotive Mechanics Technology/Technician',
  'Automotive Engineering Technology/Technician',
  'Automotive engineering',
  'Aviation / Flight Training (UND Aerospace)',
  'Aviation telecommunications engineering',
  'Aviation/Airway Management and Operations',
  'Avionics Maintenance Technology/Technician',
  'Avionics engineering',
  'Ayurvedic Medicine/Ayurveda',
  'Azari language and literature',
  'Baking and Pastry Arts/Baker/Pastry Chef',
  'Balkans Studies',
  'Ballet',
  'Baltic Languages, Literatures, and Linguistics',
  'Baltic Studies',
  'Banking affairs',
  'Banking and Financial Support Services',
  'Banking management',
  'Banking, Corporate, Finance, and Securities Law',
  'Barbering/Barber',
  'Bartending/Bartender',
  'Behavioral Aspects of Health',
  'Behavioral Sciences',
  'Belief coach',
  'Bengali Language and Literature',
  'Bible/Biblical Studies',
  'Bicycle Mechanics and Repair Technology/Technician',
  'Bilingual and Multilingual Education',
  'Biochemical Engineering',
  'Biochemistry',
  'Biochemistry and Molecular Biology',
  'Bioengineering and Biomedical Engineering',
  'Bioethics/Medical Ethics',
  'Biological and Physical Sciences',
  'Biological/Biosystems Engineering',
  'Biology',
  'Biology - Molecular Genetics',
  'Biology - Plant Physiology',
  'Biology Teacher Education',
  'Biology Technician/Biotechnology Laboratory Technician',
  'Biology-animal science',
  'Biology-plant sciences',
  'Biology/Biological Sciences',
  'Biomedical Engineering- Bioelectric',
  'Biomedical Engineering- Biomaterial',
  'Biomedical Engineering- Biomechanic',
  'Biomedical Sciences',
  'Biomedical Technology/Technician',
  'Biomedical engineering',
  'Biomedicine',
  'Biometry/Biometrics',
  'Biophysics',
  'Biopsychology',
  'Biostatistics',
  'Biotechnology',
  'Blasting/Blaster',
  'Blood Bank Technology Specialist',
  'Boilermaking/Boilermaker',
  'Bosnian, Serbian, and Croatian Languages and Literatures',
  'Botany/Plant Biology',
  'Brass Instruments',
  'Broadcast Journalism',
  'Buddhist Studies',
  'Building Construction Technology',
  'Building technician',
  'Building/Construction Site Management/Manager',
  'Building/Home/Construction Inspection/Inspector',
  'Building/Property Maintenance',
  'Bulgarian Language and Literature',
  'Burmese Language and Literature',
  'Business Administration and Management',
  'Business Family and Consumer Sciences/Human Sciences',
  'Business Machine Repair',
  'Business Statistics',
  'Business Teacher Education',
  'Business and Personal/Financial Services Marketing Operations',
  'Business management',
  'Business/Commerce',
  'Business/Corporate Communications',
  'Business/Managerial Economics',
  'Business/Office Automation/Technology/Data Entry',
  'CAD/CADD Drafting and/or Design Technology/Technician',
  'Cabinetmaking and Millwork',
  'Canadian Government and Politics',
  'Canadian History',
  'Canadian Law/Legal Studies/Jurisprudence',
  'Canadian Studies',
  'Cardiopulmonary Technology/Technologist',
  'Cardiovascular Science',
  'Cardiovascular Technology/Technologist',
  'Caribbean Studies',
  'Carpentry/Carpenter',
  'Carpet',
  'Carpet, Floor, and Tile Worker',
  'Cartography',
  'Casino Management',
  'Catalan Language and Literature',
  'Cell Biology and Anatomy',
  'Cell Physiology',
  'Cell and molecular biology',
  'Cell/Cellular Biology and Histology',
  'Cell/Cellular and Molecular Biology',
  'Cellular and molecular sciences',
  'Celtic Languages, Literatures, and Linguistics',
  'Ceramic Arts and Ceramics',
  'Ceramic Sciences and Engineering',
  'Chemical Engineering - Food Science and Technology',
  'Chemical Engineering Technology/Technician',
  'Chemical Process Technology',
  'Chemical Technology/Technician',
  'Chemical and Biomolecular Engineering',
  'Chemical engineering',
  'Chemical engineering – gas processing and transmission',
  'Chemical engineering-separation processes',
  'Chemical engineering-thermodynamics, kinetics & catalyst',
  'Chemical physics',
  'Chemistry',
  'Chemistry Teacher Education',
  'Child Care Provider/Assistant',
  'Child Care and Support Services Management',
  'Child Development',
  'Children and Youth Library Services',
  "Children's and Adolescent Literature",
  'Chinese Studies',
  'Chinese language and literature',
  'Chiropractic',
  'Chiropractic Assistant/Technician',
  'Christian Studies',
  'Cinema',
  'Cinematography and Film/Video Production',
  'City/Urban, Community and Regional Planning',
  'Civil Drafting and Civil Engineering CAD/CADD',
  'Civil Engineering - Water Resources',
  'Civil Engineering Technology/Technician',
  'Civil engineering',
  'Civil technician',
  'Classical, Ancient Mediterranean and Near Eastern Studies and Archaeology',
  'Clinical Laboratory Science/Medical Technology/Technologist',
  'Clinical Nurse Leader',
  'Clinical Nurse Specialist',
  'Clinical Nutrition/Nutritionist',
  'Clinical Pastoral Counseling/Patient Counseling',
  'Clinical Research Coordinator',
  'Clinical and Industrial Drug Development',
  'Clinical psychology',
  'Clinical, Hospital, and Managed Care Pharmacy',
  'Clinical/Medical Laboratory Assistant',
  'Clinical/Medical Laboratory Technician',
  'Clinical/Medical Social Work',
  'Cloth design',
  'Coasts, ports and marine structures',
  'Cognitive Psychology and Psycholinguistics',
  'Cognitive Science',
  'Cognitive sciences',
  'College Student Counseling and Personnel Services',
  'Combat Systems Engineering',
  'Combustion Engineering',
  'Command & Control (C3, C4I) Systems and Operations',
  'Commercial Advertisement Management',
  'Commercial Fishing',
  'Commercial Photography',
  'Commercial and Advertising Art',
  'Commonwealth Studies',
  'Communication Sciences and Disorders',
  'Communication and Information management',
  'Communication studies',
  'Communications Systems Installation and Repair Technology',
  'Communications Technology/Technician',
  'Communications law',
  'Community College Education',
  'Community Health Services/Liaison/Counseling',
  'Community Health and Preventive Medicine',
  'Community Organization and Advocacy',
  'Comparative Law',
  'Comparative Literature',
  'Comparative Psychology',
  'Comparative and Laboratory Animal Medicine',
  'Composition',
  'Computational Biology',
  'Computational Mathematics',
  'Computational Science',
  'Computational and Applied Mathematics',
  'Computer Arts',
  'Computer Engineering Technology/Technician',
  'Computer Graphics',
  'Computer Hardware Engineering',
  'Computer Hardware Technology/Technician',
  'Computer Installation and Repair Technology/Technician',
  'Computer Numerically Controlled (CNC) Machinist Technology/CNC Machinist',
  'Computer Programming, Specific Applications',
  'Computer Programming, Vendor/Product Certification',
  'Computer Programming/Programmer',
  'Computer Software Engineering',
  'Computer Software Technology/Technician',
  'Computer Support Specialist',
  'Computer Systems Analysis/Analyst',
  'Computer Systems Networking and Telecommunications',
  'Computer Teacher Education',
  'Computer Technology/Computer Systems Technology',
  'Computer Typography and Composition Equipment Operator',
  'Computer and Information Sciences',
  'Computer and Information Systems Security/Information Assurance',
  'Computer engineering',
  'Computer science',
  'Computer systems architecture',
  'Concrete Finishing/Concrete Finisher',
  'Condensed Matter and Materials Physics',
  'Conducting',
  'Conservation Biology',
  'Construction Engineering',
  'Construction Engineering Technology/Technician',
  'Construction management',
  'Construction/Heavy Equipment/Earthmoving Equipment Operation',
  'Consultation',
  'Consumer Economics',
  'Consumer Merchandising/Retailing Management',
  'Consumer Services and Advocacy',
  'Contract law',
  'Corrections',
  'Corrections Administration',
  'Cosmetology, Barber/Styling, and Nail Instructor',
  'Cosmetology/Cosmetologist',
  'Costume Design',
  'Counselor Education/School Counseling and Guidance Services',
  'Court Reporting/Court Reporter',
  'Crafts/Craft Design, Folk Art and Artisanry',
  'Creative Writing',
  'Credit Management',
  'Criminal Justice/Law Enforcement Administration',
  'Criminal Justice/Police Science',
  'Criminal Justice/Safety Studies',
  'Criminal law',
  'Criminalistics and Criminal Science',
  'Criminology',
  'Crisis management',
  'Crisis/Emergency/Disaster Management',
  'Critical Care Nursing',
  'Critical Incident Response/Special Police Operations',
  'Critical Infrastructure Protection',
  'Crop Production',
  'Culinary Arts/Chef Training',
  'Culinary Science/Culinology',
  'Cultural Anthropology',
  'Cultural Resource Management and Policy Analysis',
  'Cultural Studies/Critical Theory and Analysis',
  'Cultural and artistic management',
  'Cultural/Archaelogical Resources Protection',
  'Curriculum and Instruction',
  'Curriculum planning',
  'Custom management',
  'Customer Service Management',
  'Customer Service Support/Call Center/Teleservice Operation',
  'Customs management',
  'Cyber/Computer Forensics and Counterterrorism',
  'Cyber/Electronic Operations and Warfare',
  'Cytogenetics/Genetics/Clinical Genetics Technology/Technologist',
  'Cytotechnology/Cytotechnologist',
  'Czech Language and Literature',
  'Dairy Husbandry and Production',
  'Dairy Science',
  'Dance',
  'Dance Therapy/Therapist',
  'Danish Language and Literature',
  'Data Entry/Microcomputer Applications',
  'Data Modeling/Warehousing and Database Administration',
  'Data Processing and Data Processing Technology/Technician',
  'Date production',
  'Deaf Studies',
  'Defence management',
  'Demography and Population Studies',
  'Dental Assisting/Assistant',
  'Dental Clinical Sciences',
  'Dental Hygiene/Hygienist',
  'Dental Laboratory Technology/Technician',
  'Dental Materials',
  'Dental Public Health and Education',
  'Dental prosthesis',
  'Dentistry',
  'Design and Visual Communications',
  'Development Economics and International Development',
  'Development administration',
  'Development of preschool children',
  'Developmental Biology and Embryology',
  'Developmental Services Worker',
  'Developmental and Child Psychology',
  'Diagnostic Medical Sonography/Sonographer and Ultrasound Technician',
  'Diesel Mechanics Technology/Technician',
  'Dietetic Technician',
  'Dietetics/Dietitian',
  'Dietitian Assistant',
  'Digital Arts',
  'Digital Communication and Media/Multimedia',
  'Direct Entry Midwifery',
  'Directed Energy Systems',
  'Directing and Theatrical Production',
  'Disability Studies',
  'Dispute Resolution',
  'Diver, Professional and Instructor',
  'Divinity/Ministry',
  'Documentary Production',
  'Dog/Pet/Animal Grooming',
  'Drafting and Design Technology/Technician',
  'Drama and Dance Teacher Education',
  'Drama and Dramatics/Theatre Arts',
  'Dramatic literature',
  'Drawing',
  'Driver and Safety Teacher Education',
  'Drywall Installation/Drywaller',
  'Dutch/Flemish Language and Literature',
  'E-Commerce/Electronic Commerce',
  'E-commerce law',
  'Early Childhood Education and Teaching',
  'Earth Science Teacher Education',
  'Earth sciences',
  'Earthquake engineering',
  'East Asian Studies',
  'Ecology',
  'Ecology and Evolutionary Biology',
  'Econometrics and Quantitative Economics',
  'Economic law',
  'Economic security',
  'Economics',
  'Econphysics',
  'Education',
  'Education Policy Analysis',
  'Education management',
  'Education services',
  'Education/Teaching of Individuals Who are Developmentally Delayed',
  'Education/Teaching of Individuals in Early Childhood Special Education Programs',
  'Education/Teaching of Individuals in Elementary Special Education Programs',
  'Education/Teaching of Individuals in Junior High/Middle School Special Education Programs',
  'Education/Teaching of Individuals in Secondary Special Education Programs',
  'Education/Teaching of Individuals with Autism',
  'Education/Teaching of Individuals with Emotional Disturbances',
  'Education/Teaching of Individuals with Hearing Impairments Including Deafness',
  'Education/Teaching of Individuals with Mental Retardation',
  'Education/Teaching of Individuals with Multiple Disabilities',
  'Education/Teaching of Individuals with Specific Learning Disabilities',
  'Education/Teaching of Individuals with Speech or Language Impairments',
  'Education/Teaching of Individuals with Traumatic Brain Injuries',
  'Education/Teaching of Individuals with Vision Impairments Including Blindness',
  'Education/Teaching of the Gifted and Talented',
  'Educational Assessment, Testing, and Measurement',
  'Educational Evaluation and Research',
  'Educational Leadership and Administration',
  'Educational Statistics and Research Methods',
  'Educational psychology',
  'Educational research',
  'Educational sciences',
  'Educational technology',
  'Educational, Instructional, and Curriculum Supervision',
  'Educational/Instructional Technology',
  'Electrical Engineering - Control',
  'Electrical Engineering - Electronics',
  'Electrical Engineering - Telecommunications (Field)',
  'Electrical Engineering - Telecommunications (System)',
  'Electrical and Electronics Engineering',
  'Electrical and Power Transmission Installation/Installer',
  'Electrical engineering',
  'Electrical engineering - Digital Electronic Systems',
  'Electrical engineering - Power',
  'Electrical technician',
  'Electrical, Electronic and Communications Engineering Technology/Technician',
  'Electrical/Electronics Drafting and Electrical/Electronics CAD/CADD',
  'Electrical/Electronics Equipment Installation and Repair',
  'Electrician',
  'Electrocardiograph Technology/Technician',
  'Electrolysis/Electrology and Electrolysis Technician',
  'Electromechanical Engineering',
  'Electromechanical Technology/Electromechanical Engineering Technology',
  'Electroneurodiagnostic/Electroencephalographic Technology/Technologist',
  'Elementary Education and Teaching',
  'Elementary and Middle School Administration/Principalship',
  'Elementary education',
  'Elementary particle physics',
  'Emergency Care Attendant (EMT Ambulance)',
  'Emergency Medical Technology/Technician (EMT Paramedic)',
  'Emergency Room/Trauma Nursing',
  'Endocrinology',
  'Endodontics/Endodontology',
  'Energy Management and Systems Technology/Technician',
  'Energy architecture',
  'Energy engineering',
  'Energy optimization',
  'Energy, Environment, and Natural Resources Law',
  'Engine Machinist',
  'Engineering',
  'Engineering Acoustics',
  'Engineering Chemistry',
  'Engineering Design',
  'Engineering Management',
  'Engineering Mechanics',
  'Engineering Physics/Applied Physics',
  'Engineering Science',
  'Engineering physics',
  'Engineering sciences',
  'Engineering/Industrial Management',
  'English Literature (British and Commonwealth)',
  'English language Education',
  'English language and literature',
  'English translation',
  'English/Language Arts Teacher Education',
  'Entomology',
  'Entrepreneurship',
  'Entrepreneurship/Entrepreneurial Studies',
  'Environment technology',
  'Environmental Biology',
  'Environmental Chemistry',
  'Environmental Design/Architecture',
  'Environmental Education',
  'Environmental Engineering Technology/Environmental Technology',
  'Environmental Health',
  'Environmental Health Engineering',
  'Environmental Science',
  'Environmental Studies',
  'Environmental Toxicology',
  'Environmental design engineering',
  'Environmental engineering',
  'Environmental law',
  'Environmental/Environmental Health Engineering',
  'Epidemiology',
  'Equestrian/Equine Studies',
  'Ethics',
  'European History',
  'European Studies/Civilization',
  'Evolutionary Biology',
  'Executive Assistant/Executive Secretary',
  'Executive management',
  'Exercise Physiology',
  'Experimental Psychology',
  'Explosive Ordinance/Bomb Disposal',
  'Facial Treatment Specialist/Facialist',
  'Facilities Planning and Management',
  'Facility Management',
  'Family Practice Nurse/Nursing',
  'Family Resource Management Studies',
  'Family Systems',
  'Family and Community Services',
  'Family and Consumer Sciences/Home Economics Teacher Education',
  'Family and Consumer Sciences/Human Sciences',
  'Family and Consumer Sciences/Human Sciences Communication',
  'Family law',
  'Family studies',
  'Farm/Farm and Ranch Management',
  'Farming affairs',
  'Fashion Merchandising',
  'Fashion Modeling',
  'Fashion and Fabric Consultant',
  'Fashion/Apparel Design',
  'Fiber, Textile and Weaving Arts',
  'Fiction literature',
  'Filipino/Tagalog Language and Literature',
  'Film directing',
  'Film production',
  'Film/Cinema/Video Studies',
  'Finance',
  'Financial Forensics and Fraud Investigation',
  'Financial Mathematics',
  'Financial Planning and Services',
  'Financial and tax affairs',
  'Financial engineering',
  'Financial management',
  'Find a Major',
  'Fine and Studio Arts Management',
  'Fine/Studio Arts',
  'Fire Prevention and Safety Technology/Technician',
  'Fire Science/Fire-fighting',
  'Fire Services Administration',
  'Fire Systems Technology',
  'Fire/Arson Investigation and Prevention',
  'Fishery technology',
  'Fishing and Fisheries Sciences and Management',
  'Flagging and Traffic Control',
  'Flight Instructor',
  'Flight dynamics and control',
  'Flight security',
  'Floriculture/Floristry Operations and Management',
  'Folklore Studies',
  'Food Preparation/Professional Cooking/Kitchen Assistant',
  'Food Science',
  'Food Service, Waiter/Waitress, and Dining Room Management/Manager',
  'Food Technology and Processing',
  'Food and Nutrition Policy',
  'Food machinery engineering',
  'Food safety & health',
  'Food sciences and technology',
  'Food techology',
  'Foods, Nutrition, and Wellness Studies',
  'Foodservice Systems Administration/Management',
  'Foreign Language Teacher  Education',
  'Foreign Languages and Literatures',
  'Forensic Chemistry',
  'Forensic Science and Technology',
  'Forest Engineering',
  'Forest Management/Forest Resources Management',
  'Forest Resources Production and Management',
  'Forest Sciences and Biology',
  'Forest Technology/Technician',
  'Forestry',
  'Forestry technology',
  'Franchising and Franchise Operations',
  'French Language Teacher Education',
  'French Studies',
  'French language and literature',
  'Fundamental physics',
  'Funeral Direction/Service',
  'Funeral Service and Mortuary Science',
  'Furniture Design and Manufacturing',
  'Futurology',
  'Game and Interactive Media Design',
  'Gay/Lesbian Studies',
  'Gene/Genetic Therapy',
  'General Literature',
  'General Office Occupations and Clerical Services',
  'General Studies',
  'Genetic Counseling/Counselor',
  'Genetics',
  'Genome Sciences/Genomics',
  'Geochemistry',
  'Geochemistry and Petrology',
  'Geoelectric',
  'Geographic Information Science and Cartography',
  'Geography',
  'Geography Teacher Education',
  'Geography and rural planning',
  'Geological/Geophysical Engineering',
  'Geology',
  'Geology/Earth Science',
  'Geomagnetics',
  'Geometry/Geometric Analysis',
  'Geomorphology',
  'Geophysics',
  'Geophysics and Seismology',
  'Geotechnical and Geoenvironmental Engineering',
  'Geotechnics',
  'Geriatric Nurse/Nursing',
  'German Language Teacher Education',
  'German Studies',
  'German language and literature',
  'German translation',
  'Gerontology',
  'Glazier',
  'Global studies',
  'Golf Course Operation and Grounds Management',
  'Graphic Communications',
  'Graphic Design',
  'Graphic and Printing Equipment Operator Production',
  'Graphics',
  'Gravimetry',
  'Greenhouse Operations and Management',
  'Gunsmithing/Gunsmith',
  'HSE',
  'Hair Styling/Stylist and Hair Design',
  'Handicrafts',
  'Handmade rug',
  'Hardware',
  'Hardware engineering',
  'Hazardous Materials Information Systems Technology/Technician',
  'Hazardous Materials Management and Waste Technology/Technician',
  'Health',
  'Health Aide',
  'Health Care Management',
  'Health Communication',
  'Health Information/Medical Records Administration/Administrator',
  'Health Information/Medical Records Technology/Technician',
  'Health Law',
  'Health Occupations Teacher Education',
  'Health Policy Analysis',
  'Health Services Administration',
  'Health Teacher Education',
  'Health Unit Coordinator/Ward Clerk',
  'Health Unit Manager/Ward Supervisor',
  'Health and Physical Education/Fitness',
  'Health and Wellness',
  'Health engineering',
  'Health information technology',
  'Health/Health Care Administration/Management',
  'Health/Medical  Physics',
  'Health/Medical Claims Examiner',
  'Hearing Instrument Specialist',
  'Heating, Air Conditioning, Ventilation and Refrigeration Maintenance Technology/Technician',
  'Heating, Ventilation, Air Conditioning and Refrigeration Engineering Technology/Technician',
  'Heavy Equipment Maintenance Technology/Technician',
  'Hebrew Language and Literature',
  'Hematology Technology/Technician',
  'Herbalism/Herbalist',
  'High Performance and Custom Engine Technician/Mechanic',
  'Higher Education/Higher Education Administration',
  'Hindi Language and Literature',
  'Hindu Studies',
  'Hispanic and Latin American Languages, Literatures, and Linguistics',
  'Hispanic-American, Puerto Rican, and Mexican-American/Chicano Studies',
  'Histologic Technician',
  'Histologic Technology/Histotechnologist',
  'Historic preservation and conservation',
  'History',
  'History Teacher Education',
  'History and Philosophy of Science and Technology',
  'History and civilization of Islamic nations',
  'History and philosophy of education',
  'History of Islam',
  'History of science',
  'Holistic Health',
  'Holocaust and Related Studies',
  'Home Furnishings and Equipment Installers',
  'Home Health Aide/Home Attendant',
  'Homeland Security',
  'Homeopathic Medicine/Homeopathy',
  'Horse Husbandry/Equine Science and Management',
  'Horse breeding',
  'Horticultural Science',
  'Hospital and Health Care Facilities Administration/Management',
  'Hospitality Administration/Management',
  'Hospitality and Recreation Marketing Operations',
  'Hotel management',
  'Hotel, Motel, and Restaurant Management',
  'Hotel/Motel Administration/Management',
  'Housing and Human Environments',
  'Human Biology',
  'Human Computer Interaction',
  'Human Development and Family Studies',
  'Human Nutrition',
  'Human Resources Development',
  'Human Resources Management/Personnel Administration',
  'Human resources management',
  'Human rights',
  'Human/Medical Genetics',
  'Humanities/Humanistic Studies',
  'Hungarian/Magyar Language and Literature',
  'Hydraulic engineering',
  'Hydraulics and Fluid Power Technology/Technician',
  'Hydrology and Water Resources Science',
  'ICT',
  'Ict research',
  'Illustration',
  'Imami jurisprudence and law',
  'Immunology',
  'Imunology',
  'Indian/Native American Education',
  'Indonesian/Malay Languages and Literatures',
  'Industrial Electronics Technology/Technician',
  'Industrial Engineering - Productivity',
  'Industrial Mechanics and Maintenance Technology',
  'Industrial Radiologic Technology/Technician',
  'Industrial Safety Technology/Technician',
  'Industrial Technology/Technician',
  'Industrial and Physical Pharmacy and Cosmetic Sciences',
  'Industrial and Product Design',
  'Industrial and organizational psychology',
  'Industrial design',
  'Industrial engineering',
  'Industrial engineering-socio-economic systems',
  'Industrial management',
  'Industrial safety technician',
  'Industrial technician',
  'Informatics',
  'Information Operations/Joint Information Operations',
  'Information Resources Management',
  'Information Science/Studies',
  'Information Security',
  'Information Technology Project Management',
  'Information management',
  'Information science and knowledge studies',
  'Information technology',
  'Information/Psychological Warfare and Military Media Relations',
  'Innovation and technology management',
  'Inorganic chemistry',
  'Institutional Food Workers',
  'Instrumentation Technology/Technician',
  'Insulator',
  'Insurance',
  'Insurance affairs',
  'Insurance management',
  'Integrated Circuit Design',
  'Intellectual property law',
  'Intelligence',
  'Intercultural/Multicultural and Diversity Studies',
  'Interior Architecture',
  'Interior design',
  'Intermedia/Multimedia',
  'International Agriculture',
  'International Business',
  'International Business, Trade, and Tax Law',
  'International Business/Trade/Commerce',
  'International Economics',
  'International Finance',
  'International Law and Legal Studies',
  'International Marketing',
  'International Policy Analysis',
  'International Public Health/International Health',
  'International Relations and Affairs',
  'International and Comparative Education',
  'International and Intercultural Communication',
  'International commercial law',
  'International law',
  'International oil and gas contract management',
  'International security',
  'International/Global Studies',
  'Investments and Securities',
  'Iranian Languages, Literatures, and Linguistics',
  'Iranian architectural studies',
  'Iranian painting',
  'Iranian studies/ iranology',
  'Irish Studies',
  'Ironworking/Ironworker',
  'Irrigation engineering',
  'Islamic and economic law',
  'Islamic architecture',
  'Islamic art',
  'Islamic law and jurisprudence',
  'Islamic philosophy',
  'Islamic philosophy and mysticism',
  'Islamic philosophy and theology',
  'Islamic studies',
  'It management',
  'Italian Studies',
  'Italian language and literature',
  'Japanese Studies',
  'Japanese language and literature',
  'Jazz/Jazz Studies',
  'Jewelry Design',
  'Jewish/Judaic Studies',
  'Joint Command/Task Force (C3, C4I) Systems',
  'Journalism',
  'Junior High/Intermediate/Middle School Education and Teaching',
  'Jurisprudence and islamic religious law',
  'Justice and law',
  'Juvenile Corrections',
  'Keyboard Instruments',
  'Khmer/Cambodian Language and Literature',
  'Kindergarten/Preschool Education and Teaching',
  'Kinesiology and Exercise Science',
  'Knowledge Management',
  'Korean Language and Literature',
  'Korean Studies',
  'Kurdish language and literature',
  'Lab chemistry',
  'Labor Studies',
  'Labor and Industrial Relations',
  'Labor economics',
  'Laboratory sciences',
  'Lactation Consultant',
  'Land Use Planning and Management/Development',
  'Land affairs',
  'Landscape architecture',
  'Landscape engineering',
  'Landscaping and Groundskeeping',
  'Language Interpretation and Translation',
  'Lao Language and Literature',
  'Large Animal/Food Animal and Equine Surgery and Medicine',
  'Laser and Optical Engineering',
  'Laser and Optical Technology/Technician',
  'Latin American Studies',
  'Latin American and Caribbean Studies',
  'Latin Language and Literature',
  'Latin Teacher Education',
  'Law',
  'Law Enforcement Intelligence Analysis',
  'Law Enforcement Investigation and Interviewing',
  'Law Enforcement Record-Keeping and Evidence Management',
  'Lay Ministry',
  'Learning Sciences',
  'Legal Administrative Assistant/Secretary',
  'Legal Assistant/Paralegal',
  'Leisure studies',
  'Liberal Arts and Sciences/Liberal Studies',
  'Library and Archives Assisting',
  'Library and Information Science',
  'Licensed Practical/Vocational Nurse Training',
  'Line and railway structures engineering',
  'Lineworker',
  'Linguistics',
  'Livestock Management',
  'Locksmithing and Safe Repair',
  'Logic',
  'Logistics, Materials, and Supply Chain Management',
  'Long Term Care Administration/Management',
  'Low-Observables and Stealth Technology',
  'MBA',
  'Machine Shop Technology/Assistant',
  'Machine Tool Technology/Machinist',
  'Magnetic Resonance Imaging (MRI) Technology/Technician',
  'Maintenance engineering',
  'Majors',
  'Make-Up Artist/Specialist',
  'Make-up',
  'Mammography Technician/Technology',
  'Management',
  'Management & planning in higher education',
  'Management Information Systems',
  'Management Science',
  'Management of dryland and desert areas',
  'Management of law enforcement force',
  'Management of urban affairs',
  'Manufacturing Engineering',
  'Manufacturing Engineering Technology/Technician',
  'Marine Biology and Biological Oceanography',
  'Marine Electronic and Telecommunications',
  'Marine Maintenance/Fitter and Ship Repair Technology/Technician',
  'Marine Science/Merchant Marine Officer',
  'Marine Sciences',
  'Marine biology',
  'Marine ecology',
  'Marine electronics & communications',
  'Marine engineering',
  'Marine machinery engineering',
  'Marine management and commerce',
  'Marine transportation',
  'Maritime Law Enforcement',
  'Maritime Studies',
  'Maritime engineering',
  'Marketing Research',
  'Marketing management',
  'Marketing/Marketing Management',
  'Marriage and Family Therapy/Counseling',
  'Mason/Masonry',
  'Mass Communication/Media Studies',
  'Massage Therapy/Therapeutic Massage',
  'Master Aesthetician/Esthetician',
  'Material technician',
  'Materials Chemistry',
  'Materials Engineering',
  'Materials Science',
  'Materials and metallurgical engineering',
  'Maternal and Child Health',
  'Maternal/Child Health and Neonatal Nurse/Nursing',
  'Mathematical Biology',
  'Mathematical Statistics and Probability',
  'Mathematics',
  'Mathematics Education',
  'Mathematics Teacher Education',
  'Mathematics and Computer Science',
  'Mathematics and Statistics',
  'Mathemtics',
  'Meat Cutting/Meat Cutter',
  'Meat health and inspection',
  'Mechanical Drafting and Mechanical Drafting CAD/CADD',
  'Mechanical Engineering/Mechanical Technology/Technician',
  'Mechanical engineering',
  'Mechanical engineering -biosystems',
  'Mechanical engineering _automotive dynamical systems design',
  'Mechanical engineering _body &structure',
  'Mechanical engineering-applied mechanics(dynamic, control, vibration)',
  'Mechanical engineering-energy transformation',
  'Mechanical engineering-industrial drawing and design',
  'Mechanical engineering-manufacturing & production',
  'Mechanical engineering-solid mechanics',
  'Mechanical technician',
  'Mechatronics',
  'Mechatronics, Robotics, and Automation Engineering',
  'Media management',
  'Medical Administrative/Executive Assistant and Medical Secretary',
  'Medical Anthropology',
  'Medical Illustration/Medical Illustrator',
  'Medical Informatics',
  'Medical Insurance Coding Specialist/Coder',
  'Medical Insurance Specialist/Medical Biller',
  'Medical Microbiology and Bacteriology',
  'Medical Nanotechnology',
  'Medical Office Assistant/Specialist',
  'Medical Office Computer Specialist/Assistant',
  'Medical Office Management/Administration',
  'Medical Physics',
  'Medical Radiologic Technology/Science - Radiation Therapist',
  'Medical Reception/Receptionist',
  'Medical Scientist',
  'Medical Staff Services Technology/Technician',
  'Medical Transcription/Transcriptionist',
  'Medical documents',
  'Medical emergency',
  'Medical law',
  'Medical/Clinical Assistant',
  'Medical/Health Management and Clinical Assistant/Specialist',
  'Medication Aide',
  'Medicinal Chemistry',
  'Medicinal and Pharmaceutical Chemistry',
  'Medicinal plants production',
  'Medicine',
  'Medieval and Renaissance Studies',
  'Medium/Heavy Vehicle and Truck Technology/Technician',
  'Meeting and Event Planning',
  'Mental Health Counseling/Counselor',
  'Merchandising and Buying Operations',
  'Metal Building Assembly/Assembler',
  'Metal Fabricator',
  'Metal Industry',
  'Metal and Jewelry Arts',
  'Metallurgical Engineering',
  'Metallurgical Technology/Technician',
  'Meteorology',
  'Microbial and Eukaryotic Genetics',
  'Microbial biotechnology',
  'Microbiology',
  'Microbiology and Immunology',
  'Midwifery',
  'Military History',
  'Military Information Systems Technology',
  'Mineral processing',
  'Mining Technology/Technician',
  'Mining and Mineral Engineering',
  'Mining engineering',
  'Mining engineering-exploitation',
  'Mining engineering-exploration',
  'Mining engineering-mineral processing',
  'Mining engineering-rock mechanics',
  'Mining technician',
  'Missile and Space Systems Technology',
  'Missions/Missionary Studies and Missiology',
  'Mobil Crane Operation/Operator',
  'Modeling, Virtual Environments and Simulation',
  'Modeling, simulation and control',
  'Modern Greek Language and Literature',
  'Molecular Biochemistry',
  'Molecular Biology',
  'Molecular Biophysics',
  'Molecular Genetics',
  'Molecular Medicine',
  'Molecular Pharmacology',
  'Molecular Physiology',
  'Molecular Toxicology',
  'Mongolian Language and Literature',
  'Montessori Teacher Education',
  'Mortuary Science and Embalming/Embalmer',
  'Motorcycle Maintenance and Repair Technology/Technician',
  'Movement Therapy and Movement Education',
  'Multicultural Education',
  'Multimedia',
  'Multimedia studies',
  'Munitions Systems/Ordinance Technology',
  'Museology/Museum Studies',
  'Museum studies',
  'Music',
  'Music History, Literature, and Theory',
  'Music Management',
  'Music Pedagogy',
  'Music Performance',
  'Music Teacher Education',
  'Music Technology',
  'Music Theory and Composition',
  'Music Therapy/Therapist',
  'Musical Instrument Fabrication and Repair',
  'Musical Theatre',
  'Musicology and Ethnomusicology',
  'Mycology',
  'Nail Technician/Specialist and Manicurist',
  'Nanobiotechnology',
  'Nanochemistry',
  'Nanotechnology',
  'Nanotechnology-nanoelectronics',
  'Nanotechnology-nanomaterials',
  'National Security Policy Studies',
  'Natural Products Chemistry and Pharmacognosy',
  'Natural Resource Economics',
  'Natural Resource Recreation and Tourism',
  'Natural Resources Law Enforcement and Protective Services',
  'Natural Resources Management and Policy',
  'Natural Resources/Conservation',
  'Natural Sciences',
  'Natural resources engineering',
  'Natural resources engineering - environmental',
  'Natural resources engineering - fisheries',
  'Natural resources engineering - forestry',
  'Natural resources engineering - rangeland and watershed',
  'Natural resources engineering - wood and paper',
  'Naturopathic Medicine/Naturopathy',
  'Naval Architecture and Marine Engineering',
  'Naval architecture engineering',
  'Near and Middle Eastern Studies',
  'Network and System Administration/Administrator',
  'Neuroanatomy',
  'Neurobiology and Anatomy',
  'Neurobiology and Behavior',
  'Neuropharmacology',
  'Neuroscience',
  'Non-Profit/Public/Organizational Management',
  'Norwegian Language and Literature',
  'Nuclear Engineering Technology/Technician',
  'Nuclear Medical Technology/Technologist',
  'Nuclear Physics',
  'Nuclear engineering',
  'Nuclear medicine technology',
  'Nuclear/Nuclear Power Technology/Technician',
  'Nurse Anesthetist',
  'Nurse Midwife/Nursing Midwifery',
  'Nursing',
  'Nursing Administration',
  'Nursing Assistant/Aide and Patient Care Assistant/Aide',
  'Nursing Education',
  'Nursing Practice',
  'Nursing Science',
  'Nutrition Sciences',
  'Nutrition science',
  'Occupation',
  'Occupational Health and Industrial Hygiene',
  'Occupational Safety and Health Technology/Technician',
  'Occupational Therapist Assistant',
  'Occupational Therapy/Therapist',
  'Occupational and Environmental Health Nursing',
  'Occupational health and safety',
  'Occupational therapy',
  'Ocean Engineering',
  'Oceanography',
  'Oceanography, Chemical and Physical',
  'Office Management and Supervision',
  'Oil and gas law',
  'Oncology and Cancer Biology',
  'Operating room',
  'Operating room technology',
  'Operational Oceanography',
  'Operations Management and Supervision',
  'Operations Research',
  'Ophthalmic Laboratory Technology/Technician',
  'Ophthalmic Technician/Technologist',
  'Optical engineering',
  'Opticianry/Ophthalmic Dispensing Optician',
  'Optics/Optical Sciences',
  'Optometric Technician/Assistant',
  'Optometry',
  'Oral Biology and Oral and Maxillofacial Pathology',
  'Oral/Maxillofacial Surgery',
  'Organic chemistry',
  'Organizational Behavior Studies',
  'Organizational Communication',
  'Organizational Leadership',
  'Ornamental Horticulture',
  'Orthodontics/Orthodontology',
  'Orthoptics/Orthoptist',
  'Orthotist/Prosthetist',
  'Osteopathic Medicine/Osteopathy',
  'Outdoor Education',
  'Pacific Area/Pacific Rim Studies',
  'Packaging Science',
  'Painting',
  'Painting/Painter and Wall Coverer',
  'Paleontology',
  'Palliative Care Nursing',
  'Paper Science and Engineering',
  'Parasitology',
  'Parks, Recreation and Leisure Facilities Management',
  'Parks, Recreation and Leisure Studies',
  'Parts and Warehousing Operations and Maintenance Technology/Technician',
  'Parts, Warehousing, and Inventory Management Operations',
  'Passive defense',
  'Pastoral Studies/Counseling',
  'Pathology/Experimental Pathology',
  'Pathology/Pathologist Assistant',
  'Peace Studies and Conflict Resolution',
  'Pediatric Dentistry/Pedodontics',
  'Pediatric Nurse/Nursing',
  'Percussion Instruments',
  'Perfusion Technology/Perfusionist',
  'Periodontics/Periodontology',
  'Perioperative/Operating Room and Surgical Nurse/Nursing',
  'Permanent Cosmetics/Makeup and Tattooing',
  'Persian language and literature',
  'Personality Psychology',
  'Petrochemical engineering',
  'Petrochemical technician',
  'Petroleum Technology/Technician',
  'Petroleum engineering',
  'Pharmaceutical Marketing and Management',
  'Pharmaceutical Quality Assurance',
  'Pharmaceutical Sciences',
  'Pharmaceutics and Drug Design',
  'Pharmacoeconomics/Pharmaceutical Economics',
  'Pharmacology',
  'Pharmacology and Toxicology',
  'Pharmacy',
  'Pharmacy Administration and Pharmacy Policy and Regulatory Affairs',
  'Pharmacy Technician/Assistant',
  'Philosophy',
  'Philosophy and Religious Studies',
  'Philosophy of religion',
  'Philosophy of science',
  'Phlebotomy Technician/Phlebotomist',
  'Photobiology',
  'Photographic and Film/Video Technology/Technician and Assistant',
  'Photography',
  'Photojournalism',
  'Photonics',
  'Physical Chemistry',
  'Physical Education Teaching and Coaching',
  'Physical Fitness Technician',
  'Physical Sciences',
  'Physical Therapy Technician/Assistant',
  'Physical Therapy/Therapist',
  'Physical and Biological Anthropology',
  'Physician Assistant',
  'Physics',
  'Physics Teacher Education',
  'Physics-thin film materials research',
  'Physiological Psychology/Psychobiology',
  'Physiology',
  'Physiotherapy',
  'Pipefitting/Pipefitter and Sprinkler Fitter',
  'Plane electronics',
  'Plane maintanance',
  'Plane telecommunication',
  'Planetary Astronomy and Science',
  'Plant Genetics',
  'Plant Molecular Biology',
  'Plant Nursery Operations and Management',
  'Plant Pathology/Phytopathology',
  'Plant Physiology',
  'Plant Protection and Integrated Pest Management',
  'Plant Sciences',
  'Plant production engineering',
  'Plant production technology',
  'Plasma and High-Temperature Physics',
  'Plastics and Polymer Engineering Technology/Technician',
  'Platemaker/Imager',
  'Playing Iranian music',
  'Playing world music',
  'Playwriting and Screenwriting',
  'Plumbing Technology/Plumber',
  'Podiatric Medicine/Podiatry',
  'Polarity Therapy',
  'Polish Language and Literature',
  'Polish Studies',
  'Political Communication',
  'Political Economy',
  'Political Science and Government',
  'Political geography',
  'Political science',
  'Political science - International Relations',
  'Polymer Chemistry',
  'Polymer engineering',
  'Polymer/Plastics Engineering',
  'Polysomnography',
  'Population Biology',
  'Portuguese Language and Literature',
  'Pottery',
  'Poultry Science',
  'Pre-Chiropractic Studies',
  'Pre-Dentistry Studies',
  'Pre-Engineering',
  'Pre-Law Studies',
  'Pre-Medicine/Pre-Medical Studies',
  'Pre-Nursing Studies',
  'Pre-Occupational Therapy Studies',
  'Pre-Optometry Studies',
  'Pre-Pharmacy Studies',
  'Pre-Physical Therapy Studies',
  'Pre-Theology/Pre-Ministerial Studies',
  'Pre-Veterinary Studies',
  'Prepress/Desktop Publishing and Digital Imaging Design',
  'Printing Management',
  'Printing Press Operator',
  'Printing and Publishing',
  'Printmaking',
  'Private law',
  'Process design',
  'Professional, Technical, Business, and Scientific Writing',
  'Programs for Foreign Lawyers',
  'Project and construction management',
  'Project management',
  'Prosthetics and orthotics',
  'Prosthodontics/Prosthodontology',
  'Protective Services Operations',
  'Psychiatric/Mental Health Nurse/Nursing',
  'Psychiatric/Mental Health Services Technician',
  'Psychology',
  'Psychology Teacher Education',
  'Psychology and education of exceptional children',
  'Psychometrics',
  'Psychometrics and Quantitative Psychology',
  'Psychopharmacology',
  'Public Finance',
  'Public Health Education and Promotion',
  'Public Health/Community Nurse/Nursing',
  'Public Policy Analysis',
  'Public Relations/Image Management',
  'Public administration',
  'Public affairs',
  'Public health',
  'Public law',
  'Public relations',
  'Public/Applied History',
  'Publishing',
  'Punjabi Language and Literature',
  'Puppet Theatre',
  'Pupulation studies',
  'Purchasing, Procurement/Acquisitions and Contracts Management',
  'Pure Chemistry',
  'Quality Control Technology/Technician',
  'Quran and hadith sciences',
  'Quran teacher training',
  'Rabbinical Studies',
  'Radar Communications and Systems Technology',
  'Radiation Biology/Radiobiology',
  'Radiation Protection/Health Physics Technician',
  'Radiation therapy technology',
  'Radio',
  'Radio and Television',
  'Radio and Television Broadcasting Technology/Technician',
  'Radiologic Technology/Science - Radiographer',
  'Radiologist Assistant',
  'Radiology technology',
  'Rail transport engineering',
  'Railroad and Railway Transportation',
  'Railway',
  'Railway engineering',
  'Railway machine engineering',
  'Railway operation engineering',
  'Range Science and Management',
  'Rangeland and watershed technology',
  'Reading Teacher Education',
  'Real Estate',
  'Real Estate Development',
  'Receptionist',
  'Recording Arts Technology/Technician',
  'Recreation Vehicle (RV) Service Technician',
  'Refinement',
  'Regional Studies (US, Canadian, Foreign)',
  'Registered Nursing/Registered Nurse',
  'Rehabilitation Aide',
  'Rehabilitation Science',
  'Reiki',
  'Religion/Religious Studies',
  'Religions and mysticism',
  'Religious Education',
  'Religious studies',
  'Religious tourism',
  'Religious/Sacred Music',
  'Remote sensing and gis',
  'Renal/Dialysis Technologist/Technician',
  'Reproductive Biology',
  'Research Methodology and Quantitative Methods',
  'Research and Development Management',
  'Resort Management',
  'Respiratory Care Therapy/Therapist',
  'Respiratory Therapy Technician/Assistant',
  'Restaurant, Culinary, and Catering Management/Manager',
  'Restaurant/Food Services Management',
  'Restoration of historical monuments',
  'Restoration of monuments',
  'Retail Management',
  'Retailing and Retail Operations',
  'Rhetoric and Composition',
  'Robotics Technology/Technician',
  'Romanian Language and Literature',
  'Roofer',
  'Rural Sociology',
  'Rural development',
  'Russian Studies',
  'Russian language and literature',
  'Russian, Central European, East European and Eurasian Studies',
  'Safety and technical inspection engineering',
  'Safety engineering',
  'Sales and Marketing Operations/Marketing and Distribution   Teacher Education',
  'Sales, Distribution, and Marketing Operations',
  'Salon/Beauty Salon Management/Manager',
  'Sanskrit and Classical Indian Languages, Literatures, and Linguistics',
  'Scandinavian Languages, Literatures, and Linguistics',
  'Scandinavian Studies',
  'School Librarian/School Library Media Specialist',
  'Science Teacher Education/General Science Teacher Education',
  'Science, Technology and Society',
  'Sculpture',
  'Secondary Education and Teaching',
  'Secondary School Administration/Principalship',
  'Securities Services Administration/Management',
  'Security System Installation, Repair, and Inspection Technology/Technician',
  'Security and Loss Prevention Services',
  'Security researcher',
  'Security technical science',
  'Seismology',
  'Selling Skills and Sales Operations',
  'Semiconductor Manufacturing Technology',
  'Sericulture',
  'Sheet Metal Technology/Sheetworking',
  'Shipbuilding engineering',
  'Shipping and port management',
  'Shoe, Boot and Leather Repair',
  'Sign Language Interpretation and Translation',
  'Signal/Geospatial Intelligence',
  'Slavic Studies',
  'Slovak Language and Literature',
  'Small Business Administration/Management',
  'Small Engine Mechanics and Repair Technology/Technician',
  'Small business management',
  'Small/Companion Animal Surgery and Medicine',
  'Social Psychology',
  'Social Science Teacher Education',
  'Social Studies Teacher Education',
  'Social and Philosophical Foundations of Education',
  'Social communication sciences',
  'Social planning and cooperation',
  'Social policy',
  'Social sciences',
  'Social sciences philosophy',
  'Social sciences research',
  'Social services management',
  'Social welfare planning',
  'Social work',
  'Sociology',
  'Sociology and Anthropology',
  'Software',
  'Software engineering',
  'Soil Chemistry and Physics',
  'Soil Microbiology',
  'Soil Science and Agronomy',
  'Soil sciences',
  'Solar Energy Technology/Technician',
  'Solid state physics',
  'Somatic Bodywork',
  'South Asian Studies',
  'Southeast Asian Studies',
  'Space Systems Operations',
  'Space engineering',
  'Spanish',
  'Spanish Language Teacher Education',
  'Spanish and Iberian Studies',
  'Spanish language and literature',
  'Special Education and Teaching',
  'Special Products Marketing Operations',
  'Speech Communication and Rhetoric',
  'Speech Teacher Education',
  'Speech pathology',
  'Speech-Language Pathology Assistant',
  'Speech-Language Pathology/Pathologist',
  'Sport and Fitness Administration/Management',
  'Sport science and physical education',
  'Sports Communication',
  'Sports Studies',
  'Sports engineering',
  'Stage Design',
  'Statistics',
  'Sterile Processing Technology/Technician',
  'Strategic Intelligence',
  'Strategic defence studies',
  'Strategic management',
  'Stringed Instruments',
  'Structural Biology',
  'Structural engineering',
  'Substance Abuse/Addiction Counseling',
  'Superintendency and Educational System Administration',
  'Supply chain management',
  'Surgical Technology/Technologist',
  'Surveying Technology/Surveying',
  'Surveying engineering',
  'Suspension and Debarment Investigation',
  'Sustainability Studies',
  'Swedish Language and Literature',
  'System optimization',
  'System, Networking, and LAN/WAN Management/Manager',
  'Systematic Biology/Biological Systematics',
  'Systems Engineering',
  'Systems Science and Theory',
  'Talmudic Studies',
  'Tamil Language and Literature',
  'Tax Law/Taxation',
  'Taxation',
  'Taxidermy/Taxidermist',
  'Teacher Assistant/Aide',
  'Teacher Education, Multiple Levels',
  'Teaching English as a Second or Foreign Language/ESL Language Instructor',
  'Teaching French as a Second or Foreign Language',
  'Technical Teacher Education',
  'Technical Theatre/Theatre Design and Technology',
  'Technical and Scientific Communication',
  'Technology Teacher Education/Industrial Arts Teacher Education',
  'Technology engineering & rural development',
  'Technology management',
  'Telecommunication',
  'Telecommunications Engineering',
  'Telecommunications Management',
  'Telecommunications Technology/Technician',
  'Television and digital arts',
  'Terrorism and Counterterrorism Operations',
  'Textile Science',
  'Textile Sciences and Engineering',
  'Textile design and printing',
  'Textile engineering',
  'Thai Language and Literature',
  'Theatre Literature, History and Criticism',
  'Theatre/Theatre Arts Management',
  'Theology/Theological Studies',
  'Theoretical Chemistry',
  'Theoretical and Mathematical Physics',
  'Therapeutic Recreation/Recreational Therapy',
  'Tibetan Language and Literature',
  'Tibetan Studies',
  'Tissue Engineering',
  'Tool and Die Technology/Technician',
  'Topology and Foundations',
  'Tourism',
  'Tourism Promotion Operations',
  'Tourism and Travel Services Management',
  'Tourism and Travel Services Marketing Operations',
  'Tourism industry',
  'Tourism management',
  'Tourism planning',
  'Tourism services',
  'Toxicology',
  'Trade and Industrial Teacher Education',
  'Traditional Chinese Medicine and Chinese Herbology',
  'Traditional art',
  'Traffic, Customs, and Transportation Clerk/Technician',
  'Training and Human Resource Develpment',
  'Transport phenomena',
  'Transportation and highway engineering',
  'Transportation management',
  'Transportation/Mobility Management',
  'Trap production technology',
  'Truck and Bus Driver/Commercial Vehicle Operator and Instructor',
  'Turf and Turfgrass Management',
  'Turkish language and literature',
  'Ukraine Studies',
  'Ukrainian Language and Literature',
  'Undersea Warfare',
  'Upholstery/Upholsterer',
  'Ural-Altaic and Central Asian Studies',
  'Uralic Languages, Literatures, and Linguistics',
  'Urban Education and Leadership',
  'Urban Forestry',
  'Urban Ministry',
  'Urban Studies/Affairs',
  'Urban design',
  'Urban engineering',
  'Urban management',
  'Urban planning',
  'Urdu language and literature',
  'Vector Biology and Control of Diseases',
  'Vehicle Emissions Inspection and Maintenance Technology/Technician',
  'Vehicle and Vehicle Parts and Accessories Marketing Operations',
  'Veterinary Anatomy',
  'Veterinary Infectious Diseases',
  'Veterinary Microbiology and Immunobiology',
  'Veterinary Pathology and Pathobiology',
  'Veterinary Physiology',
  'Veterinary Preventive Medicine, Epidemiology, and Public Health',
  'Veterinary Sciences/Veterinary Clinical Sciences',
  'Veterinary Toxicology and Pharmacology',
  'Veterinary laboratory science',
  'Veterinary medicine',
  'Veterinary/Animal Health Technology/Technician and Veterinary Assistant',
  'Vietnamese Language and Literature',
  'Virology',
  'Vision Science/Physiological Optics',
  'Visual Communication',
  'Visual and Performing Arts',
  'Viticulture and Enology',
  'Vocational Rehabilitation Counseling/Counselor',
  'Voice and Opera',
  'Waldorf/Steiner Teacher Education',
  'Watchmaking and Jewelrymaking',
  'Water Quality and Wastewater Treatment Management and Recycling Technology/Technician',
  'Water Resources Engineering',
  'Water science and engineering',
  'Water, Wetlands, and Marine Resources Management',
  'Watering technology',
  'Web Page, Digital/Multimedia and Information Resources Design',
  'Web/Multimedia Management and Webmaster',
  'Welding Engineering Technology/Technician',
  'Welding Technology/Welder',
  'Well Drilling/Driller',
  'Western European Studies',
  'Wildland/Forest Firefighting and Investigation',
  'Wildlife Biology',
  'Wildlife, Fish and Wildlands Science and Management',
  'Wine Steward/Sommelier',
  'Women studies',
  "Women's Health Nurse/Nursing",
  "Women's Ministry",
  "Women's Studies",
  'Wood Science and Wood Products/Pulp and Paper Technology',
  'Wood technology',
  'Woodwind Instruments',
  'Woodworking',
  'Word Processing',
  'Work relations',
  'Writing',
  'Writing and painting',
  'Yoga Teacher Training/Yoga Therapy',
  'Youth Ministry',
  'Youth Services/Administration',
  'Youth studies',
  'Zoology/Animal Biology',
  'aesthetics/philosophy of art',
  'bioinformatics',
  'ergonomics',
  'food industry machines engineering',
  'jurisprudence and criminal law',
  'jurisprudence and private law',
  'librarianship',
  'training of political promoters'
] as const

export const topicsData: Topic[] = topicTitles.map((title) => createTopic(title))
