import type { Topic } from './types'

// Predefined topics with their related universities
export const topicsData: Topic[] = [
  {
    id: 'art',
    name: 'art',
    display_name: 'Art & Design',
    description: 'Visual arts, graphic design, fine arts, and creative disciplines',
    universities: [
      {
        id: 'risd',
        name: 'Rhode Island School of Design',
        display_name: 'Rhode Island School of Design',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.risd.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Providence',
        region: 'Rhode Island',
      },
      {
        id: 'parsons',
        name: 'Parsons School of Design',
        display_name: 'Parsons School of Design',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.newschool.edu/parsons',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'New York',
        region: 'New York',
      },
      {
        id: 'central-saint-martins',
        name: 'Central Saint Martins',
        display_name: 'Central Saint Martins',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.arts.ac.uk/csm',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'London',
        region: 'England',
      },
      {
        id: 'royal-college-art',
        name: 'Royal College of Art',
        display_name: 'Royal College of Art',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.rca.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'London',
        region: 'England',
      },
      {
        id: 'ecole-des-beaux-arts',
        name: 'École des Beaux-Arts',
        display_name: 'École des Beaux-Arts',
        country_code: 'FR',
        type: 'education',
        homepage_url: 'https://www.beauxartsparis.fr',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Paris',
        region: 'Île-de-France',
      },
      {
        id: 'bauhaus',
        name: 'Bauhaus University Weimar',
        display_name: 'Bauhaus University Weimar',
        country_code: 'DE',
        type: 'education',
        homepage_url: 'https://www.uni-weimar.de',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Weimar',
        region: 'Thuringia',
      },
      {
        id: 'tehran-art',
        name: 'University of Tehran - Faculty of Fine Arts',
        display_name: 'University of Tehran - Faculty of Fine Arts',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
    ],
  },
  {
    id: 'computer-science',
    name: 'computer-science',
    display_name: 'Computer Science',
    description: 'Programming, software engineering, artificial intelligence, and computer systems',
    universities: [
      {
        id: 'mit',
        name: 'Massachusetts Institute of Technology',
        display_name: 'Massachusetts Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.mit.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'stanford',
        name: 'Stanford University',
        display_name: 'Stanford University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.stanford.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Stanford',
        region: 'California',
      },
      {
        id: 'cmu',
        name: 'Carnegie Mellon University',
        display_name: 'Carnegie Mellon University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.cmu.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Pittsburgh',
        region: 'Pennsylvania',
      },
      {
        id: 'tehran-cs',
        name: 'University of Tehran - Computer Science',
        display_name: 'University of Tehran - Computer Science',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'sharif-cs',
        name: 'Sharif University of Technology - Computer Science',
        display_name: 'Sharif University of Technology - Computer Science',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.sharif.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'amirkabir-cs',
        name: 'Amirkabir University of Technology - Computer Science',
        display_name: 'Amirkabir University of Technology - Computer Science',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.aut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'berkeley-cs',
        name: 'UC Berkeley - Computer Science',
        display_name: 'UC Berkeley - Computer Science',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.berkeley.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Berkeley',
        region: 'California',
      },
      {
        id: 'cambridge-cs',
        name: 'University of Cambridge - Computer Science',
        display_name: 'University of Cambridge - Computer Science',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.cam.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'England',
      },
      {
        id: 'oxford-cs',
        name: 'University of Oxford - Computer Science',
        display_name: 'University of Oxford - Computer Science',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.ox.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Oxford',
        region: 'England',
      },
      {
        id: 'eth-zurich-cs',
        name: 'ETH Zurich - Computer Science',
        display_name: 'ETH Zurich - Computer Science',
        country_code: 'CH',
        type: 'education',
        homepage_url: 'https://www.ethz.ch',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Zurich',
        region: 'Zurich',
      },
      {
        id: 'tsinghua-cs',
        name: 'Tsinghua University - Computer Science',
        display_name: 'Tsinghua University - Computer Science',
        country_code: 'CN',
        type: 'education',
        homepage_url: 'https://www.tsinghua.edu.cn',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Beijing',
        region: 'Beijing',
      },
      {
        id: 'waterloo-cs',
        name: 'University of Waterloo - Computer Science',
        display_name: 'University of Waterloo - Computer Science',
        country_code: 'CA',
        type: 'education',
        homepage_url: 'https://www.uwaterloo.ca',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Waterloo',
        region: 'Ontario',
      },
    ],
  },
  {
    id: 'medicine',
    name: 'medicine',
    display_name: 'Medicine',
    description: 'Medical sciences, healthcare, and clinical practice',
    universities: [
      {
        id: 'harvard-med',
        name: 'Harvard Medical School',
        display_name: 'Harvard Medical School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://hms.harvard.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Boston',
        region: 'Massachusetts',
      },
      {
        id: 'johns-hopkins',
        name: 'Johns Hopkins University',
        display_name: 'Johns Hopkins University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.jhu.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Baltimore',
        region: 'Maryland',
      },
      {
        id: 'tehran-med',
        name: 'Tehran University of Medical Sciences',
        display_name: 'Tehran University of Medical Sciences',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.tums.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'shahid-beheshti-med',
        name: 'Shahid Beheshti University of Medical Sciences',
        display_name: 'Shahid Beheshti University of Medical Sciences',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.sbmu.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'mashhad-med',
        name: 'Mashhad University of Medical Sciences',
        display_name: 'Mashhad University of Medical Sciences',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.mums.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Mashhad',
        region: 'Razavi Khorasan',
      },
      {
        id: 'oxford-med',
        name: 'University of Oxford - Medical Sciences',
        display_name: 'University of Oxford - Medical Sciences',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.ox.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Oxford',
        region: 'England',
      },
      {
        id: 'cambridge-med',
        name: 'University of Cambridge - Clinical Medicine',
        display_name: 'University of Cambridge - Clinical Medicine',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.cam.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'England',
      },
      {
        id: 'karolinska-med',
        name: 'Karolinska Institute',
        display_name: 'Karolinska Institute',
        country_code: 'SE',
        type: 'education',
        homepage_url: 'https://www.ki.se',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Stockholm',
        region: 'Stockholm',
      },
      {
        id: 'tokyo-med',
        name: 'University of Tokyo - Faculty of Medicine',
        display_name: 'University of Tokyo - Faculty of Medicine',
        country_code: 'JP',
        type: 'education',
        homepage_url: 'https://www.u-tokyo.ac.jp',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tokyo',
        region: 'Tokyo',
      },
      {
        id: 'melbourne-med',
        name: 'University of Melbourne - Faculty of Medicine',
        display_name: 'University of Melbourne - Faculty of Medicine',
        country_code: 'AU',
        type: 'education',
        homepage_url: 'https://www.unimelb.edu.au',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Melbourne',
        region: 'Victoria',
      },
      {
        id: 'toronto-med',
        name: 'University of Toronto - Faculty of Medicine',
        display_name: 'University of Toronto - Faculty of Medicine',
        country_code: 'CA',
        type: 'education',
        homepage_url: 'https://www.utoronto.ca',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Toronto',
        region: 'Ontario',
      },
    ],
  },
  {
    id: 'business',
    name: 'business',
    display_name: 'Business & Management',
    description: 'Business administration, finance, marketing, and entrepreneurship',
    universities: [
      {
        id: 'wharton',
        name: 'Wharton School of the University of Pennsylvania',
        display_name: 'Wharton School of the University of Pennsylvania',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.wharton.upenn.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Philadelphia',
        region: 'Pennsylvania',
      },
      {
        id: 'harvard-business',
        name: 'Harvard Business School',
        display_name: 'Harvard Business School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.hbs.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Boston',
        region: 'Massachusetts',
      },
      {
        id: 'tehran-business',
        name: 'University of Tehran - Faculty of Management',
        display_name: 'University of Tehran - Faculty of Management',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'sharif-business',
        name: 'Sharif University - Industrial Engineering',
        display_name: 'Sharif University - Industrial Engineering',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.sharif.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'london-business',
        name: 'London Business School',
        display_name: 'London Business School',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.london.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'London',
        region: 'England',
      },
      {
        id: 'insead',
        name: 'INSEAD',
        display_name: 'INSEAD',
        country_code: 'FR',
        type: 'education',
        homepage_url: 'https://www.insead.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Fontainebleau',
        region: 'Île-de-France',
      },
      {
        id: 'wharton-europe',
        name: 'Wharton School - Europe',
        display_name: 'Wharton School - Europe',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.wharton.upenn.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Philadelphia',
        region: 'Pennsylvania',
      },
      {
        id: 'kellogg',
        name: 'Kellogg School of Management',
        display_name: 'Kellogg School of Management',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.kellogg.northwestern.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Evanston',
        region: 'Illinois',
      },
      {
        id: 'booth',
        name: 'Booth School of Business',
        display_name: 'Booth School of Business',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.chicagobooth.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Chicago',
        region: 'Illinois',
      },
      {
        id: 'sloan',
        name: 'MIT Sloan School of Management',
        display_name: 'MIT Sloan School of Management',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://mitsloan.mit.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
    ],
  },
  {
    id: 'engineering',
    name: 'engineering',
    display_name: 'Engineering',
    description: 'Mechanical, electrical, civil, and other engineering disciplines',
    universities: [
      {
        id: 'caltech',
        name: 'California Institute of Technology',
        display_name: 'California Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.caltech.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Pasadena',
        region: 'California',
      },
      {
        id: 'georgia-tech',
        name: 'Georgia Institute of Technology',
        display_name: 'Georgia Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.gatech.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Atlanta',
        region: 'Georgia',
      },
      {
        id: 'tehran-eng',
        name: 'University of Tehran - Faculty of Engineering',
        display_name: 'University of Tehran - Faculty of Engineering',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'sharif-eng',
        name: 'Sharif University of Technology - Engineering',
        display_name: 'Sharif University of Technology - Engineering',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.sharif.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'amirkabir-eng',
        name: 'Amirkabir University of Technology - Engineering',
        display_name: 'Amirkabir University of Technology - Engineering',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.aut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'imperial-eng',
        name: 'Imperial College London - Engineering',
        display_name: 'Imperial College London - Engineering',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.imperial.ac.uk',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'London',
        region: 'England',
      },
      {
        id: 'eth-zurich-eng',
        name: 'ETH Zurich - Engineering',
        display_name: 'ETH Zurich - Engineering',
        country_code: 'CH',
        type: 'education',
        homepage_url: 'https://www.ethz.ch',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Zurich',
        region: 'Zurich',
      },
      {
        id: 'nus-eng',
        name: 'National University of Singapore - Engineering',
        display_name: 'National University of Singapore - Engineering',
        country_code: 'SG',
        type: 'education',
        homepage_url: 'https://www.nus.edu.sg',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Singapore',
        region: 'Singapore',
      },
      {
        id: 'kaist-eng',
        name: 'KAIST - Engineering',
        display_name: 'KAIST - Engineering',
        country_code: 'KR',
        type: 'education',
        homepage_url: 'https://www.kaist.ac.kr',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Daejeon',
        region: 'Daejeon',
      },
      {
        id: 'iit-bombay',
        name: 'Indian Institute of Technology Bombay',
        display_name: 'Indian Institute of Technology Bombay',
        country_code: 'IN',
        type: 'education',
        homepage_url: 'https://www.iitb.ac.in',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Mumbai',
        region: 'Maharashtra',
      },
      {
        id: 'delft-eng',
        name: 'Delft University of Technology',
        display_name: 'Delft University of Technology',
        country_code: 'NL',
        type: 'education',
        homepage_url: 'https://www.tudelft.nl',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Delft',
        region: 'South Holland',
      },
    ],
  },
  {
    id: 'law',
    name: 'law',
    display_name: 'Law & Legal Studies',
    description: 'Legal studies, jurisprudence, and legal practice',
    universities: [
      {
        id: 'harvard-law',
        name: 'Harvard Law School',
        display_name: 'Harvard Law School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://hls.harvard.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'yale-law',
        name: 'Yale Law School',
        display_name: 'Yale Law School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://law.yale.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'New Haven',
        region: 'Connecticut',
      },
      {
        id: 'tehran-law',
        name: 'University of Tehran - Faculty of Law',
        display_name: 'University of Tehran - Faculty of Law',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
    ],
  },
  {
    id: 'psychology',
    name: 'psychology',
    display_name: 'Psychology',
    description: 'Human behavior, mental health, and psychological research',
    universities: [
      {
        id: 'stanford-psych',
        name: 'Stanford University - Psychology Department',
        display_name: 'Stanford University - Psychology Department',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://psychology.stanford.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Stanford',
        region: 'California',
      },
      {
        id: 'harvard-psych',
        name: 'Harvard University - Psychology Department',
        display_name: 'Harvard University - Psychology Department',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://psychology.fas.harvard.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'tehran-psych',
        name: 'University of Tehran - Psychology Department',
        display_name: 'University of Tehran - Psychology Department',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
    ],
  },
  {
    id: 'architecture',
    name: 'architecture',
    display_name: 'Architecture',
    description: 'Architectural design, urban planning, and built environment',
    universities: [
      {
        id: 'mit-arch',
        name: 'MIT - School of Architecture',
        display_name: 'MIT - School of Architecture',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://architecture.mit.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'harvard-gsd',
        name: 'Harvard Graduate School of Design',
        display_name: 'Harvard Graduate School of Design',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.gsd.harvard.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'tehran-arch',
        name: 'University of Tehran - Faculty of Architecture',
        display_name: 'University of Tehran - Faculty of Architecture',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
    ],
  },
  {
    id: 'agriculture',
    name: 'agriculture',
    display_name: 'Agriculture & Food Science',
    description: 'Agricultural sciences, food technology, and environmental studies',
    universities: [
      {
        id: 'uc-davis',
        name: 'University of California, Davis',
        display_name: 'University of California, Davis',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.ucdavis.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Davis',
        region: 'California',
      },
      {
        id: 'tehran-agri',
        name: 'University of Tehran - Faculty of Agriculture',
        display_name: 'University of Tehran - Faculty of Agriculture',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.ut.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'shiraz-agri',
        name: 'Shiraz University - Faculty of Agriculture',
        display_name: 'Shiraz University - Faculty of Agriculture',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.shirazu.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Shiraz',
        region: 'Fars',
      },
    ],
  },
  {
    id: 'pharmacy',
    name: 'pharmacy',
    display_name: 'Pharmacy & Pharmaceutical Sciences',
    description: 'Pharmaceutical sciences, drug development, and clinical pharmacy',
    universities: [
      {
        id: 'tehran-pharm',
        name: 'Tehran University of Medical Sciences - School of Pharmacy',
        display_name: 'Tehran University of Medical Sciences - School of Pharmacy',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.tums.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'shahid-beheshti-pharm',
        name: 'Shahid Beheshti University - School of Pharmacy',
        display_name: 'Shahid Beheshti University - School of Pharmacy',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.sbmu.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Tehran',
        region: 'Tehran',
      },
      {
        id: 'mashhad-pharm',
        name: 'Mashhad University of Medical Sciences - School of Pharmacy',
        display_name: 'Mashhad University of Medical Sciences - School of Pharmacy',
        country_code: 'IR',
        type: 'education',
        homepage_url: 'https://www.mums.ac.ir',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Mashhad',
        region: 'Razavi Khorasan',
      },
    ],
  },
]
