import type { Topic } from './types'

// Predefined topics with their related universities
export const topicsData: Topic[] = [
  {
    id: 'art',
    name: 'art',
    display_name: 'Art & Design',
    description: 'Visual arts, graphic design, fine arts, and creative disciplines',
    universities: [
      {
        id: 'risd',
        name: 'Rhode Island School of Design',
        display_name: 'Rhode Island School of Design',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.risd.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Providence',
        region: 'Rhode Island',
      },
      {
        id: 'parsons',
        name: 'Parsons School of Design',
        display_name: 'Parsons School of Design',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.newschool.edu/parsons',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'New York',
        region: 'New York',
      },
      {
        id: 'central-saint-martins',
        name: 'Central Saint Martins',
        display_name: 'Central Saint Martins',
        country_code: 'GB',
        type: 'education',
        homepage_url: 'https://www.arts.ac.uk/csm',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'London',
        region: 'England',
      },
    ],
  },
  {
    id: 'computer-science',
    name: 'computer-science',
    display_name: 'Computer Science',
    description: 'Programming, software engineering, artificial intelligence, and computer systems',
    universities: [
      {
        id: 'mit',
        name: 'Massachusetts Institute of Technology',
        display_name: 'Massachusetts Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.mit.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Cambridge',
        region: 'Massachusetts',
      },
      {
        id: 'stanford',
        name: 'Stanford University',
        display_name: 'Stanford University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.stanford.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Stanford',
        region: 'California',
      },
      {
        id: 'cmu',
        name: 'Carnegie Mellon University',
        display_name: 'Carnegie Mellon University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.cmu.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Pittsburgh',
        region: 'Pennsylvania',
      },
    ],
  },
  {
    id: 'medicine',
    name: 'medicine',
    display_name: 'Medicine',
    description: 'Medical sciences, healthcare, and clinical practice',
    universities: [
      {
        id: 'harvard-med',
        name: 'Harvard Medical School',
        display_name: 'Harvard Medical School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://hms.harvard.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Boston',
        region: 'Massachusetts',
      },
      {
        id: 'johns-hopkins',
        name: 'Johns Hopkins University',
        display_name: 'Johns Hopkins University',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.jhu.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Baltimore',
        region: 'Maryland',
      },
    ],
  },
  {
    id: 'business',
    name: 'business',
    display_name: 'Business & Management',
    description: 'Business administration, finance, marketing, and entrepreneurship',
    universities: [
      {
        id: 'wharton',
        name: 'Wharton School of the University of Pennsylvania',
        display_name: 'Wharton School of the University of Pennsylvania',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.wharton.upenn.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Philadelphia',
        region: 'Pennsylvania',
      },
      {
        id: 'harvard-business',
        name: 'Harvard Business School',
        display_name: 'Harvard Business School',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.hbs.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Boston',
        region: 'Massachusetts',
      },
    ],
  },
  {
    id: 'engineering',
    name: 'engineering',
    display_name: 'Engineering',
    description: 'Mechanical, electrical, civil, and other engineering disciplines',
    universities: [
      {
        id: 'caltech',
        name: 'California Institute of Technology',
        display_name: 'California Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.caltech.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Pasadena',
        region: 'California',
      },
      {
        id: 'georgia-tech',
        name: 'Georgia Institute of Technology',
        display_name: 'Georgia Institute of Technology',
        country_code: 'US',
        type: 'education',
        homepage_url: 'https://www.gatech.edu',
        image_url: '',
        image_thumbnail_url: '',
        works_count: 0,
        cited_by_count: 0,
        city: 'Atlanta',
        region: 'Georgia',
      },
    ],
  },
]
