// service/sport/sportsList.ts
export const sportsList = [
  'Archery',
  'Athletics',
  'Badminton',
  'Baseball',
  'Basketball',
  'Biathlon',
  'Bobsleigh',
  'Boxing',
  'Canoeing',
  'Cricket',
  'Cross Country Skiing',
  'Curling',
  'Cycling',
  'Diving',
  'Equestrian',
  'Fencing',
  'Figure Skating',
  'Football',
  'Golf',
  'Gymnastics',
  'Handball',
  'Hockey',
  'Judo',
  'Karate',
  'Lacrosse',
  'Mixed Martial Arts',
  'Motorsport',
  'Nordic Combined',
  'Rowing',
  'Rugby',
  'Sailing',
  'Shooting',
  'Skeleton',
  'Ski Jumping',
  'Snowboarding',
  'Soccer',
  'Softball',
  'Speed Skating',
  'Squash',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Taekwondo',
  'Tennis',
  'Track Cycling',
  'Triathlon',
  'Volleyball',
  'Water Polo',
  'Weightlifting',
  'Wrestling',
  'Yoga',
  'Ultimate Frisbee',
  'Mountain Biking',
  'Rock Climbing',
  'Skateboarding',
  'Parkour',
  'Esports',
  'Chess',
  'Dance Sport',
  'Floorball',
  'Futsal',
  'Kickboxing',
  'Powerlifting',
  'Roller Hockey',
  'Speedway',
  'Windsurfing',
  'Korfball',
  'Sepak Takraw',
  'Snowshoeing',
]
