// Country dial codes with emoji flags
export interface CountryDialCode {
  name: string
  code: string // ISO 3166-1 alpha-2 code
  dialCode: string // Phone dial code (e.g., "+1", "+44")
  emoji: string
}

export const countryDialCodes: CountryDialCode[] = [
  { name: 'Afghanistan', code: 'AF', dialCode: '+93', emoji: '🇦🇫' },
  { name: 'Albania', code: 'AL', dialCode: '+355', emoji: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', dialCode: '+213', emoji: '🇩🇿' },
  { name: 'Angola', code: 'AO', dialCode: '+244', emoji: '🇦🇴' },
  { name: 'Argentina', code: 'AR', dialCode: '+54', emoji: '🇦🇷' },
  { name: 'Armenia', code: 'AM', dialCode: '+374', emoji: '🇦🇲' },
  { name: 'Australia', code: 'AU', dialCode: '+61', emoji: '🇦🇺' },
  { name: 'Austria', code: 'AT', dialCode: '+43', emoji: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', emoji: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', dialCode: '+1', emoji: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', dialCode: '+973', emoji: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880', emoji: '🇧🇩' },
  { name: 'Barbados', code: 'BB', dialCode: '+1', emoji: '🇧🇧' },
  { name: 'Belarus', code: 'BY', dialCode: '+375', emoji: '🇧🇾' },
  { name: 'Belgium', code: 'BE', dialCode: '+32', emoji: '🇧🇪' },
  { name: 'Belize', code: 'BZ', dialCode: '+501', emoji: '🇧🇿' },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', emoji: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387', emoji: '🇧🇦' },
  { name: 'Botswana', code: 'BW', dialCode: '+267', emoji: '🇧🇼' },
  { name: 'Brazil', code: 'BR', dialCode: '+55', emoji: '🇧🇷' },
  { name: 'Brunei', code: 'BN', dialCode: '+673', emoji: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', emoji: '🇧🇬' },
  { name: 'Cambodia', code: 'KH', dialCode: '+855', emoji: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', dialCode: '+237', emoji: '🇨🇲' },
  { name: 'Canada', code: 'CA', dialCode: '+1', emoji: '🇨🇦' },
  { name: 'Chile', code: 'CL', dialCode: '+56', emoji: '🇨🇱' },
  { name: 'China', code: 'CN', dialCode: '+86', emoji: '🇨🇳' },
  { name: 'Colombia', code: 'CO', dialCode: '+57', emoji: '🇨🇴' },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', emoji: '🇨🇷' },
  { name: 'Croatia', code: 'HR', dialCode: '+385', emoji: '🇭🇷' },
  { name: 'Cuba', code: 'CU', dialCode: '+53', emoji: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', dialCode: '+357', emoji: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', dialCode: '+420', emoji: '🇨🇿' },
  { name: 'Denmark', code: 'DK', dialCode: '+45', emoji: '🇩🇰' },
  { name: 'Dominican Republic', code: 'DO', dialCode: '+1', emoji: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', emoji: '🇪🇨' },
  { name: 'Egypt', code: 'EG', dialCode: '+20', emoji: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', emoji: '🇸🇻' },
  { name: 'Estonia', code: 'EE', dialCode: '+372', emoji: '🇪🇪' },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251', emoji: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', dialCode: '+679', emoji: '🇫🇯' },
  { name: 'Finland', code: 'FI', dialCode: '+358', emoji: '🇫🇮' },
  { name: 'France', code: 'FR', dialCode: '+33', emoji: '🇫🇷' },
  { name: 'French Polynesia', code: 'PF', dialCode: '+689', emoji: '🇵🇫' },
  { name: 'Georgia', code: 'GE', dialCode: '+995', emoji: '🇬🇪' },
  { name: 'Germany', code: 'DE', dialCode: '+49', emoji: '🇩🇪' },
  { name: 'Ghana', code: 'GH', dialCode: '+233', emoji: '🇬🇭' },
  { name: 'Greece', code: 'GR', dialCode: '+30', emoji: '🇬🇷' },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', emoji: '🇬🇹' },
  { name: 'Guyana', code: 'GY', dialCode: '+592', emoji: '🇬🇾' },
  { name: 'Haiti', code: 'HT', dialCode: '+509', emoji: '🇭🇹' },
  { name: 'Honduras', code: 'HN', dialCode: '+504', emoji: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', dialCode: '+852', emoji: '🇭🇰' },
  { name: 'Hungary', code: 'HU', dialCode: '+36', emoji: '🇭🇺' },
  { name: 'Iceland', code: 'IS', dialCode: '+354', emoji: '🇮🇸' },
  { name: 'India', code: 'IN', dialCode: '+91', emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', emoji: '🇮🇩' },
  { name: 'Iran', code: 'IR', dialCode: '+98', emoji: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', dialCode: '+964', emoji: '🇮🇶' },
  { name: 'Ireland', code: 'IE', dialCode: '+353', emoji: '🇮🇪' },
  { name: 'Israel', code: 'IL', dialCode: '+972', emoji: '🇮🇱' },
  { name: 'Italy', code: 'IT', dialCode: '+39', emoji: '🇮🇹' },
  { name: 'Ivory Coast', code: 'CI', dialCode: '+225', emoji: '🇨🇮' },
  { name: 'Jamaica', code: 'JM', dialCode: '+1', emoji: '🇯🇲' },
  { name: 'Japan', code: 'JP', dialCode: '+81', emoji: '🇯🇵' },
  { name: 'Jordan', code: 'JO', dialCode: '+962', emoji: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', emoji: '🇰🇿' },
  { name: 'Kenya', code: 'KE', dialCode: '+254', emoji: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', dialCode: '+686', emoji: '🇰🇮' },
  { name: 'Kosovo', code: 'XK', dialCode: '+383', emoji: '🇽🇰' },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', emoji: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', emoji: '🇰🇬' },
  { name: 'Laos', code: 'LA', dialCode: '+856', emoji: '🇱🇦' },
  { name: 'Latvia', code: 'LV', dialCode: '+371', emoji: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', dialCode: '+961', emoji: '🇱🇧' },
  { name: 'Libya', code: 'LY', dialCode: '+218', emoji: '🇱🇾' },
  { name: 'Lithuania', code: 'LT', dialCode: '+370', emoji: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352', emoji: '🇱🇺' },
  { name: 'Madagascar', code: 'MG', dialCode: '+261', emoji: '🇲🇬' },
  { name: 'Malawi', code: 'MW', dialCode: '+265', emoji: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', dialCode: '+60', emoji: '🇲🇾' },
  { name: 'Malta', code: 'MT', dialCode: '+356', emoji: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', dialCode: '+692', emoji: '🇲🇭' },
  { name: 'Mexico', code: 'MX', dialCode: '+52', emoji: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', dialCode: '+691', emoji: '🇫🇲' },
  { name: 'Moldova', code: 'MD', dialCode: '+373', emoji: '🇲🇩' },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', emoji: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', dialCode: '+382', emoji: '🇲🇪' },
  { name: 'Morocco', code: 'MA', dialCode: '+212', emoji: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258', emoji: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', dialCode: '+95', emoji: '🇲🇲' },
  { name: 'Namibia', code: 'NA', dialCode: '+264', emoji: '🇳🇦' },
  { name: 'Nauru', code: 'NR', dialCode: '+674', emoji: '🇳🇷' },
  { name: 'Nepal', code: 'NP', dialCode: '+977', emoji: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', emoji: '🇳🇱' },
  { name: 'New Caledonia', code: 'NC', dialCode: '+687', emoji: '🇳🇨' },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64', emoji: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', emoji: '🇳🇮' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', emoji: '🇳🇬' },
  { name: 'North Macedonia', code: 'MK', dialCode: '+389', emoji: '🇲🇰' },
  { name: 'Norway', code: 'NO', dialCode: '+47', emoji: '🇳🇴' },
  { name: 'Oman', code: 'OM', dialCode: '+968', emoji: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', dialCode: '+92', emoji: '🇵🇰' },
  { name: 'Palau', code: 'PW', dialCode: '+680', emoji: '🇵🇼' },
  { name: 'Panama', code: 'PA', dialCode: '+507', emoji: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', emoji: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', emoji: '🇵🇾' },
  { name: 'Peru', code: 'PE', dialCode: '+51', emoji: '🇵🇪' },
  { name: 'Philippines', code: 'PH', dialCode: '+63', emoji: '🇵🇭' },
  { name: 'Poland', code: 'PL', dialCode: '+48', emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dialCode: '+351', emoji: '🇵🇹' },
  { name: 'Qatar', code: 'QA', dialCode: '+974', emoji: '🇶🇦' },
  { name: 'Romania', code: 'RO', dialCode: '+40', emoji: '🇷🇴' },
  { name: 'Russia', code: 'RU', dialCode: '+7', emoji: '🇷🇺' },
  { name: 'Samoa', code: 'WS', dialCode: '+685', emoji: '🇼🇸' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', emoji: '🇸🇦' },
  { name: 'Senegal', code: 'SN', dialCode: '+221', emoji: '🇸🇳' },
  { name: 'Serbia', code: 'RS', dialCode: '+381', emoji: '🇷🇸' },
  { name: 'Singapore', code: 'SG', dialCode: '+65', emoji: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', dialCode: '+421', emoji: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', dialCode: '+386', emoji: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677', emoji: '🇸🇧' },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', emoji: '🇿🇦' },
  { name: 'South Korea', code: 'KR', dialCode: '+82', emoji: '🇰🇷' },
  { name: 'Spain', code: 'ES', dialCode: '+34', emoji: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', emoji: '🇱🇰' },
  { name: 'Sudan', code: 'SD', dialCode: '+249', emoji: '🇸🇩' },
  { name: 'Suriname', code: 'SR', dialCode: '+597', emoji: '🇸🇷' },
  { name: 'Sweden', code: 'SE', dialCode: '+46', emoji: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', dialCode: '+41', emoji: '🇨🇭' },
  { name: 'Syria', code: 'SY', dialCode: '+963', emoji: '🇸🇾' },
  { name: 'Taiwan', code: 'TW', dialCode: '+886', emoji: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', dialCode: '+992', emoji: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', emoji: '🇹🇿' },
  { name: 'Thailand', code: 'TH', dialCode: '+66', emoji: '🇹🇭' },
  { name: 'Tonga', code: 'TO', dialCode: '+676', emoji: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1', emoji: '🇹🇹' },
  { name: 'Tunisia', code: 'TN', dialCode: '+216', emoji: '🇹🇳' },
  { name: 'Turkey', code: 'TR', dialCode: '+90', emoji: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993', emoji: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688', emoji: '🇹🇻' },
  { name: 'Uganda', code: 'UG', dialCode: '+256', emoji: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', dialCode: '+380', emoji: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', emoji: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', emoji: '🇬🇧' },
  { name: 'United States', code: 'US', dialCode: '+1', emoji: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', emoji: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', dialCode: '+998', emoji: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', emoji: '🇻🇺' },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', emoji: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', emoji: '🇻🇳' },
  { name: 'Yemen', code: 'YE', dialCode: '+967', emoji: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260', emoji: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263', emoji: '🇿🇼' },
]

// Helper function to get country by dial code
export function getCountryByDialCode(dialCode: string): CountryDialCode | undefined {
  return countryDialCodes.find((country) => country.dialCode === dialCode)
}

// Helper function to get country by code
export function getCountryByCode(code: string): CountryDialCode | undefined {
  return countryDialCodes.find((country) => country.code.toLowerCase() === code.toLowerCase())
}

// Default country (US)
export const defaultCountry: CountryDialCode = countryDialCodes[145]

